/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * OpenAPI spec version: 5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.docs.model;

import java.util.Objects;
import com.bnc.spti.rbo.docs.model.Metadata;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Defines a document by id and a list of metadata
 */
@ApiModel(description = "Defines a document by id and a list of metadata")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-07T11:44:33.827-04:00")
public class Document {
  @JsonProperty("content")
  private byte[] content = null;

  @JsonProperty("docId")
  private String docId = null;

  @JsonProperty("metadata")
  private List<Metadata> metadata = null;

  public Document content(byte[] content) {
    this.content = content;
    return this;
  }

   /**
   * The document&#39;s content
   * @return content
  **/
  @ApiModelProperty(value = "The document's content")
  public byte[] getContent() {
    return content;
  }

  public void setContent(byte[] content) {
    this.content = content;
  }

  public Document docId(String docId) {
    this.docId = docId;
    return this;
  }

   /**
   * The document&#39;s ID
   * @return docId
  **/
  @ApiModelProperty(value = "The document's ID")
  public String getDocId() {
    return docId;
  }

  public void setDocId(String docId) {
    this.docId = docId;
  }

  public Document metadata(List<Metadata> metadata) {
    this.metadata = metadata;
    return this;
  }

  public Document addMetadataItem(Metadata metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<Metadata>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

   /**
   * The document&#39;s metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "The document's metadata")
  public List<Metadata> getMetadata() {
    return metadata;
  }

  public void setMetadata(List<Metadata> metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Document document = (Document) o;
    return Objects.equals(this.content, document.content) &&
        Objects.equals(this.docId, document.docId) &&
        Objects.equals(this.metadata, document.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, docId, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Document {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    docId: ").append(toIndentedString(docId)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

