/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * OpenAPI spec version: 5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.docs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Defines a field&#39;s by name, sort order and type
 */
@ApiModel(description = "Defines a field's by name, sort order and type")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-07T11:44:33.827-04:00")
public class Field {
  @JsonProperty("ascending")
  private Boolean ascending = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("sortOrder")
  private Integer sortOrder = null;

  public Field ascending(Boolean ascending) {
    this.ascending = ascending;
    return this;
  }

   /**
   * The type of sorting : ascending or descending
   * @return ascending
  **/
  @ApiModelProperty(value = "The type of sorting : ascending or descending")
  public Boolean isAscending() {
    return ascending;
  }

  public void setAscending(Boolean ascending) {
    this.ascending = ascending;
  }

  public Field name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The field&#39;s name
   * @return name
  **/
  @ApiModelProperty(example = "docDtLoad", value = "The field's name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Field sortOrder(Integer sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

   /**
   * The sort order
   * @return sortOrder
  **/
  @ApiModelProperty(example = "1", value = "The sort order")
  public Integer getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(Integer sortOrder) {
    this.sortOrder = sortOrder;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Field field = (Field) o;
    return Objects.equals(this.ascending, field.ascending) &&
        Objects.equals(this.name, field.name) &&
        Objects.equals(this.sortOrder, field.sortOrder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ascending, name, sortOrder);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Field {\n");
    
    sb.append("    ascending: ").append(toIndentedString(ascending)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

