/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * OpenAPI spec version: 5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.docs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Defines document&#39;s metadata&#39;s by name and value
 */
@ApiModel(description = "Defines document's metadata's by name and value")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-07T11:44:33.827-04:00")
public class Metadata {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("value")
  private Object value = null;

  public Metadata name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The metadata&#39;s name
   * @return name
  **/
  @ApiModelProperty(example = "docDtLoad", value = "The metadata's name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Metadata type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The metadata&#39;s type
   * @return type
  **/
  @ApiModelProperty(example = "String", value = "The metadata's type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Metadata value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * The metadata&#39;s&#39;s value
   * @return value
  **/
  @ApiModelProperty(example = "\"2019-01-21\"", value = "The metadata's's value")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Metadata metadata = (Metadata) o;
    return Objects.equals(this.name, metadata.name) &&
        Objects.equals(this.type, metadata.type) &&
        Objects.equals(this.value, metadata.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Metadata {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

