/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * OpenAPI spec version: 5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.docs.model;

import java.util.Objects;
import com.bnc.spti.rbo.docs.model.Document;
import com.bnc.spti.rbo.docs.model.SearchDetails;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SearchResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-07T11:44:33.827-04:00")
public class SearchResult {
  @JsonProperty("documents")
  private List<Document> documents = null;

  @JsonProperty("searchDetails")
  private SearchDetails searchDetails = null;

  public SearchResult documents(List<Document> documents) {
    this.documents = documents;
    return this;
  }

  public SearchResult addDocumentsItem(Document documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<Document>();
    }
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  @ApiModelProperty(value = "")
  public List<Document> getDocuments() {
    return documents;
  }

  public void setDocuments(List<Document> documents) {
    this.documents = documents;
  }

  public SearchResult searchDetails(SearchDetails searchDetails) {
    this.searchDetails = searchDetails;
    return this;
  }

   /**
   * Get searchDetails
   * @return searchDetails
  **/
  @ApiModelProperty(value = "")
  public SearchDetails getSearchDetails() {
    return searchDetails;
  }

  public void setSearchDetails(SearchDetails searchDetails) {
    this.searchDetails = searchDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResult searchResult = (SearchResult) o;
    return Objects.equals(this.documents, searchResult.documents) &&
        Objects.equals(this.searchDetails, searchResult.searchDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documents, searchDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResult {\n");
    
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    searchDetails: ").append(toIndentedString(searchDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

