/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.bnc.spti.rbo.dealer.model.EnumCntryIso2;
import com.bnc.spti.rbo.dealer.model.EnumProvCntryStd;
import com.bnc.spti.rbo.dealer.model.UnstrctrPostlAddrType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * AddressType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class AddressType {
  @JsonProperty("cntryIso2")
  private EnumCntryIso2 cntryIso2 = null;

  @JsonProperty("localityComplete")
  private String localityComplete = null;

  @JsonProperty("postalCdUnformatted")
  private String postalCdUnformatted = null;

  @JsonProperty("provCntryStd")
  private EnumProvCntryStd provCntryStd = null;

  @JsonProperty("unstrctrPostlAddrType")
  private UnstrctrPostlAddrType unstrctrPostlAddrType = null;

  public AddressType cntryIso2(EnumCntryIso2 cntryIso2) {
    this.cntryIso2 = cntryIso2;
    return this;
  }

   /**
   * Get cntryIso2
   * @return cntryIso2
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumCntryIso2 getCntryIso2() {
    return cntryIso2;
  }

  public void setCntryIso2(EnumCntryIso2 cntryIso2) {
    this.cntryIso2 = cntryIso2;
  }

  public AddressType localityComplete(String localityComplete) {
    this.localityComplete = localityComplete;
    return this;
  }

   /**
   * Get localityComplete
   * @return localityComplete
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLocalityComplete() {
    return localityComplete;
  }

  public void setLocalityComplete(String localityComplete) {
    this.localityComplete = localityComplete;
  }

  public AddressType postalCdUnformatted(String postalCdUnformatted) {
    this.postalCdUnformatted = postalCdUnformatted;
    return this;
  }

   /**
   * Get postalCdUnformatted
   * @return postalCdUnformatted
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPostalCdUnformatted() {
    return postalCdUnformatted;
  }

  public void setPostalCdUnformatted(String postalCdUnformatted) {
    this.postalCdUnformatted = postalCdUnformatted;
  }

  public AddressType provCntryStd(EnumProvCntryStd provCntryStd) {
    this.provCntryStd = provCntryStd;
    return this;
  }

   /**
   * Get provCntryStd
   * @return provCntryStd
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumProvCntryStd getProvCntryStd() {
    return provCntryStd;
  }

  public void setProvCntryStd(EnumProvCntryStd provCntryStd) {
    this.provCntryStd = provCntryStd;
  }

  public AddressType unstrctrPostlAddrType(UnstrctrPostlAddrType unstrctrPostlAddrType) {
    this.unstrctrPostlAddrType = unstrctrPostlAddrType;
    return this;
  }

   /**
   * Get unstrctrPostlAddrType
   * @return unstrctrPostlAddrType
  **/
  @ApiModelProperty(required = true, value = "")
  public UnstrctrPostlAddrType getUnstrctrPostlAddrType() {
    return unstrctrPostlAddrType;
  }

  public void setUnstrctrPostlAddrType(UnstrctrPostlAddrType unstrctrPostlAddrType) {
    this.unstrctrPostlAddrType = unstrctrPostlAddrType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressType addressType = (AddressType) o;
    return Objects.equals(this.cntryIso2, addressType.cntryIso2) &&
        Objects.equals(this.localityComplete, addressType.localityComplete) &&
        Objects.equals(this.postalCdUnformatted, addressType.postalCdUnformatted) &&
        Objects.equals(this.provCntryStd, addressType.provCntryStd) &&
        Objects.equals(this.unstrctrPostlAddrType, addressType.unstrctrPostlAddrType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cntryIso2, localityComplete, postalCdUnformatted, provCntryStd, unstrctrPostlAddrType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressType {\n");
    
    sb.append("    cntryIso2: ").append(toIndentedString(cntryIso2)).append("\n");
    sb.append("    localityComplete: ").append(toIndentedString(localityComplete)).append("\n");
    sb.append("    postalCdUnformatted: ").append(toIndentedString(postalCdUnformatted)).append("\n");
    sb.append("    provCntryStd: ").append(toIndentedString(provCntryStd)).append("\n");
    sb.append("    unstrctrPostlAddrType: ").append(toIndentedString(unstrctrPostlAddrType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

