/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.bnc.spti.rbo.dealer.model.IndividualNameType;
import com.bnc.spti.rbo.dealer.model.IndividualType;
import com.bnc.spti.rbo.dealer.model.PartyAddressType;
import com.bnc.spti.rbo.dealer.model.PtyElectronicCtcInfoType;
import com.bnc.spti.rbo.dealer.model.PtyTelecommunicationType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * AdvisorType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class AdvisorType {
  @JsonProperty("partyAddresses")
  private List<PartyAddressType> partyAddresses = new ArrayList<PartyAddressType>();

  @JsonProperty("ptyElectronicCtcInfos")
  private List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos = new ArrayList<PtyElectronicCtcInfoType>();

  @JsonProperty("ptyTelecommunications")
  private List<PtyTelecommunicationType> ptyTelecommunications = new ArrayList<PtyTelecommunicationType>();

  @JsonProperty("name")
  private IndividualNameType name = null;

  @JsonProperty("preferredContactLanguageCode")
  private String preferredContactLanguageCode = null;

  @JsonProperty("advisorCode")
  private String advisorCode = null;

  public AdvisorType partyAddresses(List<PartyAddressType> partyAddresses) {
    this.partyAddresses = partyAddresses;
    return this;
  }

  public AdvisorType addPartyAddressesItem(PartyAddressType partyAddressesItem) {
    this.partyAddresses.add(partyAddressesItem);
    return this;
  }

   /**
   * Get partyAddresses
   * @return partyAddresses
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PartyAddressType> getPartyAddresses() {
    return partyAddresses;
  }

  public void setPartyAddresses(List<PartyAddressType> partyAddresses) {
    this.partyAddresses = partyAddresses;
  }

  public AdvisorType ptyElectronicCtcInfos(List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos) {
    this.ptyElectronicCtcInfos = ptyElectronicCtcInfos;
    return this;
  }

  public AdvisorType addPtyElectronicCtcInfosItem(PtyElectronicCtcInfoType ptyElectronicCtcInfosItem) {
    this.ptyElectronicCtcInfos.add(ptyElectronicCtcInfosItem);
    return this;
  }

   /**
   * Get ptyElectronicCtcInfos
   * @return ptyElectronicCtcInfos
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PtyElectronicCtcInfoType> getPtyElectronicCtcInfos() {
    return ptyElectronicCtcInfos;
  }

  public void setPtyElectronicCtcInfos(List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos) {
    this.ptyElectronicCtcInfos = ptyElectronicCtcInfos;
  }

  public AdvisorType ptyTelecommunications(List<PtyTelecommunicationType> ptyTelecommunications) {
    this.ptyTelecommunications = ptyTelecommunications;
    return this;
  }

  public AdvisorType addPtyTelecommunicationsItem(PtyTelecommunicationType ptyTelecommunicationsItem) {
    this.ptyTelecommunications.add(ptyTelecommunicationsItem);
    return this;
  }

   /**
   * Get ptyTelecommunications
   * @return ptyTelecommunications
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PtyTelecommunicationType> getPtyTelecommunications() {
    return ptyTelecommunications;
  }

  public void setPtyTelecommunications(List<PtyTelecommunicationType> ptyTelecommunications) {
    this.ptyTelecommunications = ptyTelecommunications;
  }

  public AdvisorType name(IndividualNameType name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public IndividualNameType getName() {
    return name;
  }

  public void setName(IndividualNameType name) {
    this.name = name;
  }

  public AdvisorType preferredContactLanguageCode(String preferredContactLanguageCode) {
    this.preferredContactLanguageCode = preferredContactLanguageCode;
    return this;
  }

   /**
   * Get preferredContactLanguageCode
   * @return preferredContactLanguageCode
  **/
  @ApiModelProperty(value = "")
  public String getPreferredContactLanguageCode() {
    return preferredContactLanguageCode;
  }

  public void setPreferredContactLanguageCode(String preferredContactLanguageCode) {
    this.preferredContactLanguageCode = preferredContactLanguageCode;
  }

  public AdvisorType advisorCode(String advisorCode) {
    this.advisorCode = advisorCode;
    return this;
  }

   /**
   * Get advisorCode
   * @return advisorCode
  **/
  @ApiModelProperty(value = "")
  public String getAdvisorCode() {
    return advisorCode;
  }

  public void setAdvisorCode(String advisorCode) {
    this.advisorCode = advisorCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvisorType advisorType = (AdvisorType) o;
    return Objects.equals(this.partyAddresses, advisorType.partyAddresses) &&
        Objects.equals(this.ptyElectronicCtcInfos, advisorType.ptyElectronicCtcInfos) &&
        Objects.equals(this.ptyTelecommunications, advisorType.ptyTelecommunications) &&
        Objects.equals(this.name, advisorType.name) &&
        Objects.equals(this.preferredContactLanguageCode, advisorType.preferredContactLanguageCode) &&
        Objects.equals(this.advisorCode, advisorType.advisorCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyAddresses, ptyElectronicCtcInfos, ptyTelecommunications, name, preferredContactLanguageCode, advisorCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdvisorType {\n");
    
    sb.append("    partyAddresses: ").append(toIndentedString(partyAddresses)).append("\n");
    sb.append("    ptyElectronicCtcInfos: ").append(toIndentedString(ptyElectronicCtcInfos)).append("\n");
    sb.append("    ptyTelecommunications: ").append(toIndentedString(ptyTelecommunications)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    preferredContactLanguageCode: ").append(toIndentedString(preferredContactLanguageCode)).append("\n");
    sb.append("    advisorCode: ").append(toIndentedString(advisorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

