/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.bnc.spti.rbo.dealer.model.Description;
import com.bnc.spti.rbo.dealer.model.ManagerType;
import com.bnc.spti.rbo.dealer.model.OrganizationUnitType;
import com.bnc.spti.rbo.dealer.model.PartyAddressType;
import com.bnc.spti.rbo.dealer.model.PtyElectronicCtcInfoType;
import com.bnc.spti.rbo.dealer.model.PtyTelecommunicationType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * BranchType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class BranchType {
  @JsonProperty("partyAddresses")
  private List<PartyAddressType> partyAddresses = new ArrayList<PartyAddressType>();

  @JsonProperty("ptyElectronicCtcInfos")
  private List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos = new ArrayList<PtyElectronicCtcInfoType>();

  @JsonProperty("ptyTelecommunications")
  private List<PtyTelecommunicationType> ptyTelecommunications = new ArrayList<PtyTelecommunicationType>();

  @JsonProperty("orgUnitCPARegionCd")
  private String orgUnitCPARegionCd = null;

  @JsonProperty("orgUnitCPARegionName")
  private Description orgUnitCPARegionName = null;

  @JsonProperty("orgUnitCd")
  private String orgUnitCd = null;

  @JsonProperty("orgUnitId")
  private Integer orgUnitId = null;

  @JsonProperty("orgUnitLangCd")
  private String orgUnitLangCd = null;

  @JsonProperty("orgUnitName")
  private Description orgUnitName = null;

  @JsonProperty("orgUnitTypeCd")
  private String orgUnitTypeCd = null;

  @JsonProperty("manager")
  private ManagerType manager = null;

  public BranchType partyAddresses(List<PartyAddressType> partyAddresses) {
    this.partyAddresses = partyAddresses;
    return this;
  }

  public BranchType addPartyAddressesItem(PartyAddressType partyAddressesItem) {
    this.partyAddresses.add(partyAddressesItem);
    return this;
  }

   /**
   * Get partyAddresses
   * @return partyAddresses
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PartyAddressType> getPartyAddresses() {
    return partyAddresses;
  }

  public void setPartyAddresses(List<PartyAddressType> partyAddresses) {
    this.partyAddresses = partyAddresses;
  }

  public BranchType ptyElectronicCtcInfos(List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos) {
    this.ptyElectronicCtcInfos = ptyElectronicCtcInfos;
    return this;
  }

  public BranchType addPtyElectronicCtcInfosItem(PtyElectronicCtcInfoType ptyElectronicCtcInfosItem) {
    this.ptyElectronicCtcInfos.add(ptyElectronicCtcInfosItem);
    return this;
  }

   /**
   * Get ptyElectronicCtcInfos
   * @return ptyElectronicCtcInfos
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PtyElectronicCtcInfoType> getPtyElectronicCtcInfos() {
    return ptyElectronicCtcInfos;
  }

  public void setPtyElectronicCtcInfos(List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos) {
    this.ptyElectronicCtcInfos = ptyElectronicCtcInfos;
  }

  public BranchType ptyTelecommunications(List<PtyTelecommunicationType> ptyTelecommunications) {
    this.ptyTelecommunications = ptyTelecommunications;
    return this;
  }

  public BranchType addPtyTelecommunicationsItem(PtyTelecommunicationType ptyTelecommunicationsItem) {
    this.ptyTelecommunications.add(ptyTelecommunicationsItem);
    return this;
  }

   /**
   * Get ptyTelecommunications
   * @return ptyTelecommunications
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PtyTelecommunicationType> getPtyTelecommunications() {
    return ptyTelecommunications;
  }

  public void setPtyTelecommunications(List<PtyTelecommunicationType> ptyTelecommunications) {
    this.ptyTelecommunications = ptyTelecommunications;
  }

  public BranchType orgUnitCPARegionCd(String orgUnitCPARegionCd) {
    this.orgUnitCPARegionCd = orgUnitCPARegionCd;
    return this;
  }

   /**
   * Get orgUnitCPARegionCd
   * @return orgUnitCPARegionCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitCPARegionCd() {
    return orgUnitCPARegionCd;
  }

  public void setOrgUnitCPARegionCd(String orgUnitCPARegionCd) {
    this.orgUnitCPARegionCd = orgUnitCPARegionCd;
  }

  public BranchType orgUnitCPARegionName(Description orgUnitCPARegionName) {
    this.orgUnitCPARegionName = orgUnitCPARegionName;
    return this;
  }

   /**
   * Get orgUnitCPARegionName
   * @return orgUnitCPARegionName
  **/
  @ApiModelProperty(required = true, value = "")
  public Description getOrgUnitCPARegionName() {
    return orgUnitCPARegionName;
  }

  public void setOrgUnitCPARegionName(Description orgUnitCPARegionName) {
    this.orgUnitCPARegionName = orgUnitCPARegionName;
  }

  public BranchType orgUnitCd(String orgUnitCd) {
    this.orgUnitCd = orgUnitCd;
    return this;
  }

   /**
   * Get orgUnitCd
   * @return orgUnitCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitCd() {
    return orgUnitCd;
  }

  public void setOrgUnitCd(String orgUnitCd) {
    this.orgUnitCd = orgUnitCd;
  }

  public BranchType orgUnitId(Integer orgUnitId) {
    this.orgUnitId = orgUnitId;
    return this;
  }

   /**
   * Get orgUnitId
   * @return orgUnitId
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrgUnitId() {
    return orgUnitId;
  }

  public void setOrgUnitId(Integer orgUnitId) {
    this.orgUnitId = orgUnitId;
  }

  public BranchType orgUnitLangCd(String orgUnitLangCd) {
    this.orgUnitLangCd = orgUnitLangCd;
    return this;
  }

   /**
   * Get orgUnitLangCd
   * @return orgUnitLangCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitLangCd() {
    return orgUnitLangCd;
  }

  public void setOrgUnitLangCd(String orgUnitLangCd) {
    this.orgUnitLangCd = orgUnitLangCd;
  }

  public BranchType orgUnitName(Description orgUnitName) {
    this.orgUnitName = orgUnitName;
    return this;
  }

   /**
   * Get orgUnitName
   * @return orgUnitName
  **/
  @ApiModelProperty(required = true, value = "")
  public Description getOrgUnitName() {
    return orgUnitName;
  }

  public void setOrgUnitName(Description orgUnitName) {
    this.orgUnitName = orgUnitName;
  }

  public BranchType orgUnitTypeCd(String orgUnitTypeCd) {
    this.orgUnitTypeCd = orgUnitTypeCd;
    return this;
  }

   /**
   * Get orgUnitTypeCd
   * @return orgUnitTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitTypeCd() {
    return orgUnitTypeCd;
  }

  public void setOrgUnitTypeCd(String orgUnitTypeCd) {
    this.orgUnitTypeCd = orgUnitTypeCd;
  }

  public BranchType manager(ManagerType manager) {
    this.manager = manager;
    return this;
  }

   /**
   * Get manager
   * @return manager
  **/
  @ApiModelProperty(required = true, value = "")
  public ManagerType getManager() {
    return manager;
  }

  public void setManager(ManagerType manager) {
    this.manager = manager;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BranchType branchType = (BranchType) o;
    return Objects.equals(this.partyAddresses, branchType.partyAddresses) &&
        Objects.equals(this.ptyElectronicCtcInfos, branchType.ptyElectronicCtcInfos) &&
        Objects.equals(this.ptyTelecommunications, branchType.ptyTelecommunications) &&
        Objects.equals(this.orgUnitCPARegionCd, branchType.orgUnitCPARegionCd) &&
        Objects.equals(this.orgUnitCPARegionName, branchType.orgUnitCPARegionName) &&
        Objects.equals(this.orgUnitCd, branchType.orgUnitCd) &&
        Objects.equals(this.orgUnitId, branchType.orgUnitId) &&
        Objects.equals(this.orgUnitLangCd, branchType.orgUnitLangCd) &&
        Objects.equals(this.orgUnitName, branchType.orgUnitName) &&
        Objects.equals(this.orgUnitTypeCd, branchType.orgUnitTypeCd) &&
        Objects.equals(this.manager, branchType.manager);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyAddresses, ptyElectronicCtcInfos, ptyTelecommunications, orgUnitCPARegionCd, orgUnitCPARegionName, orgUnitCd, orgUnitId, orgUnitLangCd, orgUnitName, orgUnitTypeCd, manager);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BranchType {\n");
    
    sb.append("    partyAddresses: ").append(toIndentedString(partyAddresses)).append("\n");
    sb.append("    ptyElectronicCtcInfos: ").append(toIndentedString(ptyElectronicCtcInfos)).append("\n");
    sb.append("    ptyTelecommunications: ").append(toIndentedString(ptyTelecommunications)).append("\n");
    sb.append("    orgUnitCPARegionCd: ").append(toIndentedString(orgUnitCPARegionCd)).append("\n");
    sb.append("    orgUnitCPARegionName: ").append(toIndentedString(orgUnitCPARegionName)).append("\n");
    sb.append("    orgUnitCd: ").append(toIndentedString(orgUnitCd)).append("\n");
    sb.append("    orgUnitId: ").append(toIndentedString(orgUnitId)).append("\n");
    sb.append("    orgUnitLangCd: ").append(toIndentedString(orgUnitLangCd)).append("\n");
    sb.append("    orgUnitName: ").append(toIndentedString(orgUnitName)).append("\n");
    sb.append("    orgUnitTypeCd: ").append(toIndentedString(orgUnitTypeCd)).append("\n");
    sb.append("    manager: ").append(toIndentedString(manager)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

