/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.bnc.spti.rbo.dealer.model.Description;
import com.bnc.spti.rbo.dealer.model.EnumOrgHomeJurisdGeoAreaCd;
import com.bnc.spti.rbo.dealer.model.OrganizationType;
import com.bnc.spti.rbo.dealer.model.OrganizationUnitType;
import com.bnc.spti.rbo.dealer.model.PartyAddressType;
import com.bnc.spti.rbo.dealer.model.PtyElectronicCtcInfoType;
import com.bnc.spti.rbo.dealer.model.PtyTelecommunicationType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * CompanyType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class CompanyType {
  @JsonProperty("partyAddresses")
  private List<PartyAddressType> partyAddresses = new ArrayList<PartyAddressType>();

  @JsonProperty("ptyElectronicCtcInfos")
  private List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos = new ArrayList<PtyElectronicCtcInfoType>();

  @JsonProperty("ptyTelecommunications")
  private List<PtyTelecommunicationType> ptyTelecommunications = new ArrayList<PtyTelecommunicationType>();

  @JsonProperty("orgConstitutionDt")
  private Date orgConstitutionDt = null;

  @JsonProperty("orgDtFiscalYearEndDay")
  private Integer orgDtFiscalYearEndDay = null;

  @JsonProperty("orgDtFiscalYearEndMth")
  private Integer orgDtFiscalYearEndMth = null;

  @JsonProperty("orgHomeJurisdGeoAreaCd")
  private EnumOrgHomeJurisdGeoAreaCd orgHomeJurisdGeoAreaCd = null;

  @JsonProperty("orgHomeJurisdGeoAreaTypeCd")
  private String orgHomeJurisdGeoAreaTypeCd = null;

  @JsonProperty("orgLglFormCd")
  private String orgLglFormCd = null;

  @JsonProperty("orgLglFormTypeCd")
  private String orgLglFormTypeCd = null;

  @JsonProperty("organizationName")
  private Description organizationName = null;

  @JsonProperty("orgUnitCPARegionCd")
  private String orgUnitCPARegionCd = null;

  @JsonProperty("orgUnitCPARegionName")
  private Description orgUnitCPARegionName = null;

  @JsonProperty("orgUnitCd")
  private String orgUnitCd = null;

  @JsonProperty("orgUnitId")
  private Integer orgUnitId = null;

  @JsonProperty("orgUnitLangCd")
  private String orgUnitLangCd = null;

  @JsonProperty("orgUnitName")
  private Description orgUnitName = null;

  @JsonProperty("orgUnitTypeCd")
  private String orgUnitTypeCd = null;

  public CompanyType partyAddresses(List<PartyAddressType> partyAddresses) {
    this.partyAddresses = partyAddresses;
    return this;
  }

  public CompanyType addPartyAddressesItem(PartyAddressType partyAddressesItem) {
    this.partyAddresses.add(partyAddressesItem);
    return this;
  }

   /**
   * Get partyAddresses
   * @return partyAddresses
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PartyAddressType> getPartyAddresses() {
    return partyAddresses;
  }

  public void setPartyAddresses(List<PartyAddressType> partyAddresses) {
    this.partyAddresses = partyAddresses;
  }

  public CompanyType ptyElectronicCtcInfos(List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos) {
    this.ptyElectronicCtcInfos = ptyElectronicCtcInfos;
    return this;
  }

  public CompanyType addPtyElectronicCtcInfosItem(PtyElectronicCtcInfoType ptyElectronicCtcInfosItem) {
    this.ptyElectronicCtcInfos.add(ptyElectronicCtcInfosItem);
    return this;
  }

   /**
   * Get ptyElectronicCtcInfos
   * @return ptyElectronicCtcInfos
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PtyElectronicCtcInfoType> getPtyElectronicCtcInfos() {
    return ptyElectronicCtcInfos;
  }

  public void setPtyElectronicCtcInfos(List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos) {
    this.ptyElectronicCtcInfos = ptyElectronicCtcInfos;
  }

  public CompanyType ptyTelecommunications(List<PtyTelecommunicationType> ptyTelecommunications) {
    this.ptyTelecommunications = ptyTelecommunications;
    return this;
  }

  public CompanyType addPtyTelecommunicationsItem(PtyTelecommunicationType ptyTelecommunicationsItem) {
    this.ptyTelecommunications.add(ptyTelecommunicationsItem);
    return this;
  }

   /**
   * Get ptyTelecommunications
   * @return ptyTelecommunications
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PtyTelecommunicationType> getPtyTelecommunications() {
    return ptyTelecommunications;
  }

  public void setPtyTelecommunications(List<PtyTelecommunicationType> ptyTelecommunications) {
    this.ptyTelecommunications = ptyTelecommunications;
  }

  public CompanyType orgConstitutionDt(Date orgConstitutionDt) {
    this.orgConstitutionDt = orgConstitutionDt;
    return this;
  }

   /**
   * Get orgConstitutionDt
   * @return orgConstitutionDt
  **/
  @ApiModelProperty(required = true, value = "")
  public Date getOrgConstitutionDt() {
    return orgConstitutionDt;
  }

  public void setOrgConstitutionDt(Date orgConstitutionDt) {
    this.orgConstitutionDt = orgConstitutionDt;
  }

  public CompanyType orgDtFiscalYearEndDay(Integer orgDtFiscalYearEndDay) {
    this.orgDtFiscalYearEndDay = orgDtFiscalYearEndDay;
    return this;
  }

   /**
   * Get orgDtFiscalYearEndDay
   * @return orgDtFiscalYearEndDay
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrgDtFiscalYearEndDay() {
    return orgDtFiscalYearEndDay;
  }

  public void setOrgDtFiscalYearEndDay(Integer orgDtFiscalYearEndDay) {
    this.orgDtFiscalYearEndDay = orgDtFiscalYearEndDay;
  }

  public CompanyType orgDtFiscalYearEndMth(Integer orgDtFiscalYearEndMth) {
    this.orgDtFiscalYearEndMth = orgDtFiscalYearEndMth;
    return this;
  }

   /**
   * Get orgDtFiscalYearEndMth
   * @return orgDtFiscalYearEndMth
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrgDtFiscalYearEndMth() {
    return orgDtFiscalYearEndMth;
  }

  public void setOrgDtFiscalYearEndMth(Integer orgDtFiscalYearEndMth) {
    this.orgDtFiscalYearEndMth = orgDtFiscalYearEndMth;
  }

  public CompanyType orgHomeJurisdGeoAreaCd(EnumOrgHomeJurisdGeoAreaCd orgHomeJurisdGeoAreaCd) {
    this.orgHomeJurisdGeoAreaCd = orgHomeJurisdGeoAreaCd;
    return this;
  }

   /**
   * Get orgHomeJurisdGeoAreaCd
   * @return orgHomeJurisdGeoAreaCd
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumOrgHomeJurisdGeoAreaCd getOrgHomeJurisdGeoAreaCd() {
    return orgHomeJurisdGeoAreaCd;
  }

  public void setOrgHomeJurisdGeoAreaCd(EnumOrgHomeJurisdGeoAreaCd orgHomeJurisdGeoAreaCd) {
    this.orgHomeJurisdGeoAreaCd = orgHomeJurisdGeoAreaCd;
  }

  public CompanyType orgHomeJurisdGeoAreaTypeCd(String orgHomeJurisdGeoAreaTypeCd) {
    this.orgHomeJurisdGeoAreaTypeCd = orgHomeJurisdGeoAreaTypeCd;
    return this;
  }

   /**
   * Get orgHomeJurisdGeoAreaTypeCd
   * @return orgHomeJurisdGeoAreaTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgHomeJurisdGeoAreaTypeCd() {
    return orgHomeJurisdGeoAreaTypeCd;
  }

  public void setOrgHomeJurisdGeoAreaTypeCd(String orgHomeJurisdGeoAreaTypeCd) {
    this.orgHomeJurisdGeoAreaTypeCd = orgHomeJurisdGeoAreaTypeCd;
  }

  public CompanyType orgLglFormCd(String orgLglFormCd) {
    this.orgLglFormCd = orgLglFormCd;
    return this;
  }

   /**
   * Get orgLglFormCd
   * @return orgLglFormCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgLglFormCd() {
    return orgLglFormCd;
  }

  public void setOrgLglFormCd(String orgLglFormCd) {
    this.orgLglFormCd = orgLglFormCd;
  }

  public CompanyType orgLglFormTypeCd(String orgLglFormTypeCd) {
    this.orgLglFormTypeCd = orgLglFormTypeCd;
    return this;
  }

   /**
   * Get orgLglFormTypeCd
   * @return orgLglFormTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgLglFormTypeCd() {
    return orgLglFormTypeCd;
  }

  public void setOrgLglFormTypeCd(String orgLglFormTypeCd) {
    this.orgLglFormTypeCd = orgLglFormTypeCd;
  }

  public CompanyType organizationName(Description organizationName) {
    this.organizationName = organizationName;
    return this;
  }

   /**
   * Get organizationName
   * @return organizationName
  **/
  @ApiModelProperty(required = true, value = "")
  public Description getOrganizationName() {
    return organizationName;
  }

  public void setOrganizationName(Description organizationName) {
    this.organizationName = organizationName;
  }

  public CompanyType orgUnitCPARegionCd(String orgUnitCPARegionCd) {
    this.orgUnitCPARegionCd = orgUnitCPARegionCd;
    return this;
  }

   /**
   * Get orgUnitCPARegionCd
   * @return orgUnitCPARegionCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitCPARegionCd() {
    return orgUnitCPARegionCd;
  }

  public void setOrgUnitCPARegionCd(String orgUnitCPARegionCd) {
    this.orgUnitCPARegionCd = orgUnitCPARegionCd;
  }

  public CompanyType orgUnitCPARegionName(Description orgUnitCPARegionName) {
    this.orgUnitCPARegionName = orgUnitCPARegionName;
    return this;
  }

   /**
   * Get orgUnitCPARegionName
   * @return orgUnitCPARegionName
  **/
  @ApiModelProperty(required = true, value = "")
  public Description getOrgUnitCPARegionName() {
    return orgUnitCPARegionName;
  }

  public void setOrgUnitCPARegionName(Description orgUnitCPARegionName) {
    this.orgUnitCPARegionName = orgUnitCPARegionName;
  }

  public CompanyType orgUnitCd(String orgUnitCd) {
    this.orgUnitCd = orgUnitCd;
    return this;
  }

   /**
   * Get orgUnitCd
   * @return orgUnitCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitCd() {
    return orgUnitCd;
  }

  public void setOrgUnitCd(String orgUnitCd) {
    this.orgUnitCd = orgUnitCd;
  }

  public CompanyType orgUnitId(Integer orgUnitId) {
    this.orgUnitId = orgUnitId;
    return this;
  }

   /**
   * Get orgUnitId
   * @return orgUnitId
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrgUnitId() {
    return orgUnitId;
  }

  public void setOrgUnitId(Integer orgUnitId) {
    this.orgUnitId = orgUnitId;
  }

  public CompanyType orgUnitLangCd(String orgUnitLangCd) {
    this.orgUnitLangCd = orgUnitLangCd;
    return this;
  }

   /**
   * Get orgUnitLangCd
   * @return orgUnitLangCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitLangCd() {
    return orgUnitLangCd;
  }

  public void setOrgUnitLangCd(String orgUnitLangCd) {
    this.orgUnitLangCd = orgUnitLangCd;
  }

  public CompanyType orgUnitName(Description orgUnitName) {
    this.orgUnitName = orgUnitName;
    return this;
  }

   /**
   * Get orgUnitName
   * @return orgUnitName
  **/
  @ApiModelProperty(required = true, value = "")
  public Description getOrgUnitName() {
    return orgUnitName;
  }

  public void setOrgUnitName(Description orgUnitName) {
    this.orgUnitName = orgUnitName;
  }

  public CompanyType orgUnitTypeCd(String orgUnitTypeCd) {
    this.orgUnitTypeCd = orgUnitTypeCd;
    return this;
  }

   /**
   * Get orgUnitTypeCd
   * @return orgUnitTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitTypeCd() {
    return orgUnitTypeCd;
  }

  public void setOrgUnitTypeCd(String orgUnitTypeCd) {
    this.orgUnitTypeCd = orgUnitTypeCd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyType companyType = (CompanyType) o;
    return Objects.equals(this.partyAddresses, companyType.partyAddresses) &&
        Objects.equals(this.ptyElectronicCtcInfos, companyType.ptyElectronicCtcInfos) &&
        Objects.equals(this.ptyTelecommunications, companyType.ptyTelecommunications) &&
        Objects.equals(this.orgConstitutionDt, companyType.orgConstitutionDt) &&
        Objects.equals(this.orgDtFiscalYearEndDay, companyType.orgDtFiscalYearEndDay) &&
        Objects.equals(this.orgDtFiscalYearEndMth, companyType.orgDtFiscalYearEndMth) &&
        Objects.equals(this.orgHomeJurisdGeoAreaCd, companyType.orgHomeJurisdGeoAreaCd) &&
        Objects.equals(this.orgHomeJurisdGeoAreaTypeCd, companyType.orgHomeJurisdGeoAreaTypeCd) &&
        Objects.equals(this.orgLglFormCd, companyType.orgLglFormCd) &&
        Objects.equals(this.orgLglFormTypeCd, companyType.orgLglFormTypeCd) &&
        Objects.equals(this.organizationName, companyType.organizationName) &&
        Objects.equals(this.orgUnitCPARegionCd, companyType.orgUnitCPARegionCd) &&
        Objects.equals(this.orgUnitCPARegionName, companyType.orgUnitCPARegionName) &&
        Objects.equals(this.orgUnitCd, companyType.orgUnitCd) &&
        Objects.equals(this.orgUnitId, companyType.orgUnitId) &&
        Objects.equals(this.orgUnitLangCd, companyType.orgUnitLangCd) &&
        Objects.equals(this.orgUnitName, companyType.orgUnitName) &&
        Objects.equals(this.orgUnitTypeCd, companyType.orgUnitTypeCd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyAddresses, ptyElectronicCtcInfos, ptyTelecommunications, orgConstitutionDt, orgDtFiscalYearEndDay, orgDtFiscalYearEndMth, orgHomeJurisdGeoAreaCd, orgHomeJurisdGeoAreaTypeCd, orgLglFormCd, orgLglFormTypeCd, organizationName, orgUnitCPARegionCd, orgUnitCPARegionName, orgUnitCd, orgUnitId, orgUnitLangCd, orgUnitName, orgUnitTypeCd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyType {\n");
    
    sb.append("    partyAddresses: ").append(toIndentedString(partyAddresses)).append("\n");
    sb.append("    ptyElectronicCtcInfos: ").append(toIndentedString(ptyElectronicCtcInfos)).append("\n");
    sb.append("    ptyTelecommunications: ").append(toIndentedString(ptyTelecommunications)).append("\n");
    sb.append("    orgConstitutionDt: ").append(toIndentedString(orgConstitutionDt)).append("\n");
    sb.append("    orgDtFiscalYearEndDay: ").append(toIndentedString(orgDtFiscalYearEndDay)).append("\n");
    sb.append("    orgDtFiscalYearEndMth: ").append(toIndentedString(orgDtFiscalYearEndMth)).append("\n");
    sb.append("    orgHomeJurisdGeoAreaCd: ").append(toIndentedString(orgHomeJurisdGeoAreaCd)).append("\n");
    sb.append("    orgHomeJurisdGeoAreaTypeCd: ").append(toIndentedString(orgHomeJurisdGeoAreaTypeCd)).append("\n");
    sb.append("    orgLglFormCd: ").append(toIndentedString(orgLglFormCd)).append("\n");
    sb.append("    orgLglFormTypeCd: ").append(toIndentedString(orgLglFormTypeCd)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    orgUnitCPARegionCd: ").append(toIndentedString(orgUnitCPARegionCd)).append("\n");
    sb.append("    orgUnitCPARegionName: ").append(toIndentedString(orgUnitCPARegionName)).append("\n");
    sb.append("    orgUnitCd: ").append(toIndentedString(orgUnitCd)).append("\n");
    sb.append("    orgUnitId: ").append(toIndentedString(orgUnitId)).append("\n");
    sb.append("    orgUnitLangCd: ").append(toIndentedString(orgUnitLangCd)).append("\n");
    sb.append("    orgUnitName: ").append(toIndentedString(orgUnitName)).append("\n");
    sb.append("    orgUnitTypeCd: ").append(toIndentedString(orgUnitTypeCd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

