/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.bnc.spti.rbo.dealer.model.AdvisorType;
import com.bnc.spti.rbo.dealer.model.BranchType;
import com.bnc.spti.rbo.dealer.model.CompanyType;
import com.bnc.spti.rbo.dealer.model.Description;
import com.bnc.spti.rbo.dealer.model.EnumOrgHomeJurisdGeoAreaCd;
import com.bnc.spti.rbo.dealer.model.PartyAddressType;
import com.bnc.spti.rbo.dealer.model.PtyElectronicCtcInfoType;
import com.bnc.spti.rbo.dealer.model.PtyTelecommunicationType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * DealerType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class DealerType {
  @JsonProperty("partyAddresses")
  private List<PartyAddressType> partyAddresses = new ArrayList<PartyAddressType>();

  @JsonProperty("ptyElectronicCtcInfos")
  private List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos = new ArrayList<PtyElectronicCtcInfoType>();

  @JsonProperty("ptyTelecommunications")
  private List<PtyTelecommunicationType> ptyTelecommunications = new ArrayList<PtyTelecommunicationType>();

  @JsonProperty("orgConstitutionDt")
  private Date orgConstitutionDt = null;

  @JsonProperty("orgDtFiscalYearEndDay")
  private Integer orgDtFiscalYearEndDay = null;

  @JsonProperty("orgDtFiscalYearEndMth")
  private Integer orgDtFiscalYearEndMth = null;

  @JsonProperty("orgHomeJurisdGeoAreaCd")
  private EnumOrgHomeJurisdGeoAreaCd orgHomeJurisdGeoAreaCd = null;

  @JsonProperty("orgHomeJurisdGeoAreaTypeCd")
  private String orgHomeJurisdGeoAreaTypeCd = null;

  @JsonProperty("orgLglFormCd")
  private String orgLglFormCd = null;

  @JsonProperty("orgLglFormTypeCd")
  private String orgLglFormTypeCd = null;

  @JsonProperty("organizationName")
  private Description organizationName = null;

  @JsonProperty("orgUnitCPARegionCd")
  private String orgUnitCPARegionCd = null;

  @JsonProperty("orgUnitCPARegionName")
  private Description orgUnitCPARegionName = null;

  @JsonProperty("orgUnitCd")
  private String orgUnitCd = null;

  @JsonProperty("orgUnitId")
  private Integer orgUnitId = null;

  @JsonProperty("orgUnitLangCd")
  private String orgUnitLangCd = null;

  @JsonProperty("orgUnitName")
  private Description orgUnitName = null;

  @JsonProperty("orgUnitTypeCd")
  private String orgUnitTypeCd = null;

  @JsonProperty("advisors")
  private List<AdvisorType> advisors = new ArrayList<AdvisorType>();

  @JsonProperty("branches")
  private List<BranchType> branches = new ArrayList<BranchType>();

  @JsonProperty("sro")
  private CompanyType sro = null;

  @JsonProperty("protectionAgency")
  private CompanyType protectionAgency = null;

  public DealerType partyAddresses(List<PartyAddressType> partyAddresses) {
    this.partyAddresses = partyAddresses;
    return this;
  }

  public DealerType addPartyAddressesItem(PartyAddressType partyAddressesItem) {
    this.partyAddresses.add(partyAddressesItem);
    return this;
  }

   /**
   * Get partyAddresses
   * @return partyAddresses
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PartyAddressType> getPartyAddresses() {
    return partyAddresses;
  }

  public void setPartyAddresses(List<PartyAddressType> partyAddresses) {
    this.partyAddresses = partyAddresses;
  }

  public DealerType ptyElectronicCtcInfos(List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos) {
    this.ptyElectronicCtcInfos = ptyElectronicCtcInfos;
    return this;
  }

  public DealerType addPtyElectronicCtcInfosItem(PtyElectronicCtcInfoType ptyElectronicCtcInfosItem) {
    this.ptyElectronicCtcInfos.add(ptyElectronicCtcInfosItem);
    return this;
  }

   /**
   * Get ptyElectronicCtcInfos
   * @return ptyElectronicCtcInfos
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PtyElectronicCtcInfoType> getPtyElectronicCtcInfos() {
    return ptyElectronicCtcInfos;
  }

  public void setPtyElectronicCtcInfos(List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos) {
    this.ptyElectronicCtcInfos = ptyElectronicCtcInfos;
  }

  public DealerType ptyTelecommunications(List<PtyTelecommunicationType> ptyTelecommunications) {
    this.ptyTelecommunications = ptyTelecommunications;
    return this;
  }

  public DealerType addPtyTelecommunicationsItem(PtyTelecommunicationType ptyTelecommunicationsItem) {
    this.ptyTelecommunications.add(ptyTelecommunicationsItem);
    return this;
  }

   /**
   * Get ptyTelecommunications
   * @return ptyTelecommunications
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PtyTelecommunicationType> getPtyTelecommunications() {
    return ptyTelecommunications;
  }

  public void setPtyTelecommunications(List<PtyTelecommunicationType> ptyTelecommunications) {
    this.ptyTelecommunications = ptyTelecommunications;
  }

  public DealerType orgConstitutionDt(Date orgConstitutionDt) {
    this.orgConstitutionDt = orgConstitutionDt;
    return this;
  }

   /**
   * Get orgConstitutionDt
   * @return orgConstitutionDt
  **/
  @ApiModelProperty(required = true, value = "")
  public Date getOrgConstitutionDt() {
    return orgConstitutionDt;
  }

  public void setOrgConstitutionDt(Date orgConstitutionDt) {
    this.orgConstitutionDt = orgConstitutionDt;
  }

  public DealerType orgDtFiscalYearEndDay(Integer orgDtFiscalYearEndDay) {
    this.orgDtFiscalYearEndDay = orgDtFiscalYearEndDay;
    return this;
  }

   /**
   * Get orgDtFiscalYearEndDay
   * @return orgDtFiscalYearEndDay
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrgDtFiscalYearEndDay() {
    return orgDtFiscalYearEndDay;
  }

  public void setOrgDtFiscalYearEndDay(Integer orgDtFiscalYearEndDay) {
    this.orgDtFiscalYearEndDay = orgDtFiscalYearEndDay;
  }

  public DealerType orgDtFiscalYearEndMth(Integer orgDtFiscalYearEndMth) {
    this.orgDtFiscalYearEndMth = orgDtFiscalYearEndMth;
    return this;
  }

   /**
   * Get orgDtFiscalYearEndMth
   * @return orgDtFiscalYearEndMth
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrgDtFiscalYearEndMth() {
    return orgDtFiscalYearEndMth;
  }

  public void setOrgDtFiscalYearEndMth(Integer orgDtFiscalYearEndMth) {
    this.orgDtFiscalYearEndMth = orgDtFiscalYearEndMth;
  }

  public DealerType orgHomeJurisdGeoAreaCd(EnumOrgHomeJurisdGeoAreaCd orgHomeJurisdGeoAreaCd) {
    this.orgHomeJurisdGeoAreaCd = orgHomeJurisdGeoAreaCd;
    return this;
  }

   /**
   * Get orgHomeJurisdGeoAreaCd
   * @return orgHomeJurisdGeoAreaCd
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumOrgHomeJurisdGeoAreaCd getOrgHomeJurisdGeoAreaCd() {
    return orgHomeJurisdGeoAreaCd;
  }

  public void setOrgHomeJurisdGeoAreaCd(EnumOrgHomeJurisdGeoAreaCd orgHomeJurisdGeoAreaCd) {
    this.orgHomeJurisdGeoAreaCd = orgHomeJurisdGeoAreaCd;
  }

  public DealerType orgHomeJurisdGeoAreaTypeCd(String orgHomeJurisdGeoAreaTypeCd) {
    this.orgHomeJurisdGeoAreaTypeCd = orgHomeJurisdGeoAreaTypeCd;
    return this;
  }

   /**
   * Get orgHomeJurisdGeoAreaTypeCd
   * @return orgHomeJurisdGeoAreaTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgHomeJurisdGeoAreaTypeCd() {
    return orgHomeJurisdGeoAreaTypeCd;
  }

  public void setOrgHomeJurisdGeoAreaTypeCd(String orgHomeJurisdGeoAreaTypeCd) {
    this.orgHomeJurisdGeoAreaTypeCd = orgHomeJurisdGeoAreaTypeCd;
  }

  public DealerType orgLglFormCd(String orgLglFormCd) {
    this.orgLglFormCd = orgLglFormCd;
    return this;
  }

   /**
   * Get orgLglFormCd
   * @return orgLglFormCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgLglFormCd() {
    return orgLglFormCd;
  }

  public void setOrgLglFormCd(String orgLglFormCd) {
    this.orgLglFormCd = orgLglFormCd;
  }

  public DealerType orgLglFormTypeCd(String orgLglFormTypeCd) {
    this.orgLglFormTypeCd = orgLglFormTypeCd;
    return this;
  }

   /**
   * Get orgLglFormTypeCd
   * @return orgLglFormTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgLglFormTypeCd() {
    return orgLglFormTypeCd;
  }

  public void setOrgLglFormTypeCd(String orgLglFormTypeCd) {
    this.orgLglFormTypeCd = orgLglFormTypeCd;
  }

  public DealerType organizationName(Description organizationName) {
    this.organizationName = organizationName;
    return this;
  }

   /**
   * Get organizationName
   * @return organizationName
  **/
  @ApiModelProperty(required = true, value = "")
  public Description getOrganizationName() {
    return organizationName;
  }

  public void setOrganizationName(Description organizationName) {
    this.organizationName = organizationName;
  }

  public DealerType orgUnitCPARegionCd(String orgUnitCPARegionCd) {
    this.orgUnitCPARegionCd = orgUnitCPARegionCd;
    return this;
  }

   /**
   * Get orgUnitCPARegionCd
   * @return orgUnitCPARegionCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitCPARegionCd() {
    return orgUnitCPARegionCd;
  }

  public void setOrgUnitCPARegionCd(String orgUnitCPARegionCd) {
    this.orgUnitCPARegionCd = orgUnitCPARegionCd;
  }

  public DealerType orgUnitCPARegionName(Description orgUnitCPARegionName) {
    this.orgUnitCPARegionName = orgUnitCPARegionName;
    return this;
  }

   /**
   * Get orgUnitCPARegionName
   * @return orgUnitCPARegionName
  **/
  @ApiModelProperty(required = true, value = "")
  public Description getOrgUnitCPARegionName() {
    return orgUnitCPARegionName;
  }

  public void setOrgUnitCPARegionName(Description orgUnitCPARegionName) {
    this.orgUnitCPARegionName = orgUnitCPARegionName;
  }

  public DealerType orgUnitCd(String orgUnitCd) {
    this.orgUnitCd = orgUnitCd;
    return this;
  }

   /**
   * Get orgUnitCd
   * @return orgUnitCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitCd() {
    return orgUnitCd;
  }

  public void setOrgUnitCd(String orgUnitCd) {
    this.orgUnitCd = orgUnitCd;
  }

  public DealerType orgUnitId(Integer orgUnitId) {
    this.orgUnitId = orgUnitId;
    return this;
  }

   /**
   * Get orgUnitId
   * @return orgUnitId
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrgUnitId() {
    return orgUnitId;
  }

  public void setOrgUnitId(Integer orgUnitId) {
    this.orgUnitId = orgUnitId;
  }

  public DealerType orgUnitLangCd(String orgUnitLangCd) {
    this.orgUnitLangCd = orgUnitLangCd;
    return this;
  }

   /**
   * Get orgUnitLangCd
   * @return orgUnitLangCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitLangCd() {
    return orgUnitLangCd;
  }

  public void setOrgUnitLangCd(String orgUnitLangCd) {
    this.orgUnitLangCd = orgUnitLangCd;
  }

  public DealerType orgUnitName(Description orgUnitName) {
    this.orgUnitName = orgUnitName;
    return this;
  }

   /**
   * Get orgUnitName
   * @return orgUnitName
  **/
  @ApiModelProperty(required = true, value = "")
  public Description getOrgUnitName() {
    return orgUnitName;
  }

  public void setOrgUnitName(Description orgUnitName) {
    this.orgUnitName = orgUnitName;
  }

  public DealerType orgUnitTypeCd(String orgUnitTypeCd) {
    this.orgUnitTypeCd = orgUnitTypeCd;
    return this;
  }

   /**
   * Get orgUnitTypeCd
   * @return orgUnitTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgUnitTypeCd() {
    return orgUnitTypeCd;
  }

  public void setOrgUnitTypeCd(String orgUnitTypeCd) {
    this.orgUnitTypeCd = orgUnitTypeCd;
  }

  public DealerType advisors(List<AdvisorType> advisors) {
    this.advisors = advisors;
    return this;
  }

  public DealerType addAdvisorsItem(AdvisorType advisorsItem) {
    this.advisors.add(advisorsItem);
    return this;
  }

   /**
   * Get advisors
   * @return advisors
  **/
  @ApiModelProperty(required = true, value = "")
  public List<AdvisorType> getAdvisors() {
    return advisors;
  }

  public void setAdvisors(List<AdvisorType> advisors) {
    this.advisors = advisors;
  }

  public DealerType branches(List<BranchType> branches) {
    this.branches = branches;
    return this;
  }

  public DealerType addBranchesItem(BranchType branchesItem) {
    this.branches.add(branchesItem);
    return this;
  }

   /**
   * Get branches
   * @return branches
  **/
  @ApiModelProperty(required = true, value = "")
  public List<BranchType> getBranches() {
    return branches;
  }

  public void setBranches(List<BranchType> branches) {
    this.branches = branches;
  }

  public DealerType sro(CompanyType sro) {
    this.sro = sro;
    return this;
  }

   /**
   * Get sro
   * @return sro
  **/
  @ApiModelProperty(required = true, value = "")
  public CompanyType getSro() {
    return sro;
  }

  public void setSro(CompanyType sro) {
    this.sro = sro;
  }

  public DealerType protectionAgency(CompanyType protectionAgency) {
    this.protectionAgency = protectionAgency;
    return this;
  }

   /**
   * Get protectionAgency
   * @return protectionAgency
  **/
  @ApiModelProperty(required = true, value = "")
  public CompanyType getProtectionAgency() {
    return protectionAgency;
  }

  public void setProtectionAgency(CompanyType protectionAgency) {
    this.protectionAgency = protectionAgency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DealerType dealerType = (DealerType) o;
    return Objects.equals(this.partyAddresses, dealerType.partyAddresses) &&
        Objects.equals(this.ptyElectronicCtcInfos, dealerType.ptyElectronicCtcInfos) &&
        Objects.equals(this.ptyTelecommunications, dealerType.ptyTelecommunications) &&
        Objects.equals(this.orgConstitutionDt, dealerType.orgConstitutionDt) &&
        Objects.equals(this.orgDtFiscalYearEndDay, dealerType.orgDtFiscalYearEndDay) &&
        Objects.equals(this.orgDtFiscalYearEndMth, dealerType.orgDtFiscalYearEndMth) &&
        Objects.equals(this.orgHomeJurisdGeoAreaCd, dealerType.orgHomeJurisdGeoAreaCd) &&
        Objects.equals(this.orgHomeJurisdGeoAreaTypeCd, dealerType.orgHomeJurisdGeoAreaTypeCd) &&
        Objects.equals(this.orgLglFormCd, dealerType.orgLglFormCd) &&
        Objects.equals(this.orgLglFormTypeCd, dealerType.orgLglFormTypeCd) &&
        Objects.equals(this.organizationName, dealerType.organizationName) &&
        Objects.equals(this.orgUnitCPARegionCd, dealerType.orgUnitCPARegionCd) &&
        Objects.equals(this.orgUnitCPARegionName, dealerType.orgUnitCPARegionName) &&
        Objects.equals(this.orgUnitCd, dealerType.orgUnitCd) &&
        Objects.equals(this.orgUnitId, dealerType.orgUnitId) &&
        Objects.equals(this.orgUnitLangCd, dealerType.orgUnitLangCd) &&
        Objects.equals(this.orgUnitName, dealerType.orgUnitName) &&
        Objects.equals(this.orgUnitTypeCd, dealerType.orgUnitTypeCd) &&
        Objects.equals(this.advisors, dealerType.advisors) &&
        Objects.equals(this.branches, dealerType.branches) &&
        Objects.equals(this.sro, dealerType.sro) &&
        Objects.equals(this.protectionAgency, dealerType.protectionAgency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyAddresses, ptyElectronicCtcInfos, ptyTelecommunications, orgConstitutionDt, orgDtFiscalYearEndDay, orgDtFiscalYearEndMth, orgHomeJurisdGeoAreaCd, orgHomeJurisdGeoAreaTypeCd, orgLglFormCd, orgLglFormTypeCd, organizationName, orgUnitCPARegionCd, orgUnitCPARegionName, orgUnitCd, orgUnitId, orgUnitLangCd, orgUnitName, orgUnitTypeCd, advisors, branches, sro, protectionAgency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DealerType {\n");
    
    sb.append("    partyAddresses: ").append(toIndentedString(partyAddresses)).append("\n");
    sb.append("    ptyElectronicCtcInfos: ").append(toIndentedString(ptyElectronicCtcInfos)).append("\n");
    sb.append("    ptyTelecommunications: ").append(toIndentedString(ptyTelecommunications)).append("\n");
    sb.append("    orgConstitutionDt: ").append(toIndentedString(orgConstitutionDt)).append("\n");
    sb.append("    orgDtFiscalYearEndDay: ").append(toIndentedString(orgDtFiscalYearEndDay)).append("\n");
    sb.append("    orgDtFiscalYearEndMth: ").append(toIndentedString(orgDtFiscalYearEndMth)).append("\n");
    sb.append("    orgHomeJurisdGeoAreaCd: ").append(toIndentedString(orgHomeJurisdGeoAreaCd)).append("\n");
    sb.append("    orgHomeJurisdGeoAreaTypeCd: ").append(toIndentedString(orgHomeJurisdGeoAreaTypeCd)).append("\n");
    sb.append("    orgLglFormCd: ").append(toIndentedString(orgLglFormCd)).append("\n");
    sb.append("    orgLglFormTypeCd: ").append(toIndentedString(orgLglFormTypeCd)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    orgUnitCPARegionCd: ").append(toIndentedString(orgUnitCPARegionCd)).append("\n");
    sb.append("    orgUnitCPARegionName: ").append(toIndentedString(orgUnitCPARegionName)).append("\n");
    sb.append("    orgUnitCd: ").append(toIndentedString(orgUnitCd)).append("\n");
    sb.append("    orgUnitId: ").append(toIndentedString(orgUnitId)).append("\n");
    sb.append("    orgUnitLangCd: ").append(toIndentedString(orgUnitLangCd)).append("\n");
    sb.append("    orgUnitName: ").append(toIndentedString(orgUnitName)).append("\n");
    sb.append("    orgUnitTypeCd: ").append(toIndentedString(orgUnitTypeCd)).append("\n");
    sb.append("    advisors: ").append(toIndentedString(advisors)).append("\n");
    sb.append("    branches: ").append(toIndentedString(branches)).append("\n");
    sb.append("    sro: ").append(toIndentedString(sro)).append("\n");
    sb.append("    protectionAgency: ").append(toIndentedString(protectionAgency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

