/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Description
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class Description {
  @JsonProperty("english")
  private String english = null;

  @JsonProperty("french")
  private String french = null;

  public Description english(String english) {
    this.english = english;
    return this;
  }

   /**
   * Get english
   * @return english
  **/
  @ApiModelProperty(value = "")
  public String getEnglish() {
    return english;
  }

  public void setEnglish(String english) {
    this.english = english;
  }

  public Description french(String french) {
    this.french = french;
    return this;
  }

   /**
   * Get french
   * @return french
  **/
  @ApiModelProperty(value = "")
  public String getFrench() {
    return french;
  }

  public void setFrench(String french) {
    this.french = french;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Description description = (Description) o;
    return Objects.equals(this.english, description.english) &&
        Objects.equals(this.french, description.french);
  }

  @Override
  public int hashCode() {
    return Objects.hash(english, french);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Description {\n");
    
    sb.append("    english: ").append(toIndentedString(english)).append("\n");
    sb.append("    french: ").append(toIndentedString(french)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

