/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * EnumPrefContactLangCd
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-25T19:30:40.094-05:00")
public class EnumPrefContactLangCd {
  /**
   * Gets or Sets value
   */
  public enum ValueEnum {
    AA("aa"),
    
    AB("ab"),
    
    AE("ae"),
    
    AF("af"),
    
    AK("ak"),
    
    AM("am"),
    
    AN("an"),
    
    AR("ar"),
    
    AS("as"),
    
    AV("av"),
    
    AY("ay"),
    
    AZ("az"),
    
    BA("ba"),
    
    BE("be"),
    
    BG("bg"),
    
    BH("bh"),
    
    BI("bi"),
    
    BM("bm"),
    
    BN("bn"),
    
    BO("bo"),
    
    BR("br"),
    
    BS("bs"),
    
    CA("ca"),
    
    CE("ce"),
    
    CH("ch"),
    
    CO("co"),
    
    CR("cr"),
    
    CS("cs"),
    
    CU("cu"),
    
    CV("cv"),
    
    CY("cy"),
    
    DA("da"),
    
    DE("de"),
    
    DV("dv"),
    
    DZ("dz"),
    
    EE("ee"),
    
    EL("el"),
    
    EN("EN"),
    
    EO("eo"),
    
    ES("es"),
    
    ET("et"),
    
    EU("eu"),
    
    FA("fa"),
    
    FF("ff"),
    
    FI("fi"),
    
    FJ("fj"),
    
    FO("fo"),
    
    FR("FR"),
    
    FY("fy"),
    
    GA("ga"),
    
    GD("gd"),
    
    GL("gl"),
    
    GN("gn"),
    
    GU("gu"),
    
    GV("gv"),
    
    HA("ha"),
    
    HE("he"),
    
    HI("hi"),
    
    HO("ho"),
    
    HR("hr"),
    
    HT("ht"),
    
    HU("hu"),
    
    HY("hy"),
    
    HZ("hz"),
    
    IA("ia"),
    
    ID("id"),
    
    IE("ie"),
    
    IG("ig"),
    
    II("ii"),
    
    IK("ik"),
    
    INCONNU("INCONNU"),
    
    IO("io"),
    
    IS("is"),
    
    IT("it"),
    
    IU("iu"),
    
    JA("ja"),
    
    JV("jv"),
    
    KA("ka"),
    
    KG("kg"),
    
    KI("ki"),
    
    KJ("kj"),
    
    KK("kk"),
    
    KL("kl"),
    
    KM("km"),
    
    KN("kn"),
    
    KO("ko"),
    
    KR("kr"),
    
    KS("ks"),
    
    KU("ku"),
    
    KV("kv"),
    
    KW("kw"),
    
    KY("ky"),
    
    LA("la"),
    
    LB("lb"),
    
    LG("lg"),
    
    LI("li"),
    
    LN("ln"),
    
    LO("lo"),
    
    LT("lt"),
    
    LU("lu"),
    
    LV("lv"),
    
    MG("mg"),
    
    MH("mh"),
    
    MI("mi"),
    
    MK("mk"),
    
    ML("ml"),
    
    MN("mn"),
    
    MR("mr"),
    
    MS("ms"),
    
    MT("mt"),
    
    MY("my"),
    
    N_A("N/A"),
    
    N_D("N/D"),
    
    NA("na"),
    
    NB("nb"),
    
    ND("nd"),
    
    NE("ne"),
    
    NG("ng"),
    
    NL("nl"),
    
    NN("nn"),
    
    NR("nr"),
    
    NV("nv"),
    
    NY("ny"),
    
    OC("oc"),
    
    OJ("oj"),
    
    OM("om"),
    
    OR("or"),
    
    OS("os"),
    
    PA("pa"),
    
    PI("pi"),
    
    PL("pl"),
    
    PS("ps"),
    
    PT("pt"),
    
    QU("qu"),
    
    RM("rm"),
    
    RN("rn"),
    
    RO("ro"),
    
    RU("ru"),
    
    RW("rw"),
    
    SA("sa"),
    
    SC("sc"),
    
    SD("sd"),
    
    SE("se"),
    
    SG("sg"),
    
    SI("si"),
    
    SK("sk"),
    
    SL("sl"),
    
    SM("sm"),
    
    SN("sn"),
    
    SO("so"),
    
    SQ("sq"),
    
    SR("sr"),
    
    SS("ss"),
    
    ST("st"),
    
    SU("su"),
    
    SV("sv"),
    
    SW("sw"),
    
    TA("ta"),
    
    TE("te"),
    
    TG("tg"),
    
    TH("th"),
    
    TI("ti"),
    
    TK("tk"),
    
    TL("tl"),
    
    TN("tn"),
    
    TO("to"),
    
    TR("tr"),
    
    TS("ts"),
    
    TT("tt"),
    
    TW("tw"),
    
    TY("ty"),
    
    UG("ug"),
    
    UK("uk"),
    
    UR("ur"),
    
    UZ("uz"),
    
    VE("ve"),
    
    VI("vi"),
    
    VO("vo"),
    
    WA("wa"),
    
    WO("wo"),
    
    XH("xh"),
    
    YI("yi"),
    
    YO("yo"),
    
    ZA("za"),
    
    ZH("zh"),
    
    ZU("zu");

    private String value;

    ValueEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValueEnum fromValue(String text) {
      for (ValueEnum b : ValueEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("$")
  private ValueEnum value = null;

  public EnumPrefContactLangCd value(ValueEnum value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public ValueEnum getValue() {
    return value;
  }

  public void setValue(ValueEnum value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnumPrefContactLangCd enumPrefContactLangCd = (EnumPrefContactLangCd) o;
    return Objects.equals(this.value, enumPrefContactLangCd.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnumPrefContactLangCd {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

