/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * EnumPtyTlcCntryPhoneCd
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class EnumPtyTlcCntryPhoneCd {
  /**
   * Gets or Sets value
   */
  public enum ValueEnum {
    _1_242("1 242"),
    
    _1_246("1 246"),
    
    _1_264("1 264"),
    
    _1_268("1 268"),
    
    _1_284("1 284"),
    
    _1_340("1 340"),
    
    _1_345("1 345"),
    
    _1_441("1 441"),
    
    _1_473("1 473"),
    
    _1_599("1 599"),
    
    _1_649("1 649"),
    
    _1_664("1 664"),
    
    _1_670("1 670"),
    
    _1_671("1 671"),
    
    _1_684("1 684"),
    
    _1_758("1 758"),
    
    _1_767("1 767"),
    
    _1_784("1 784"),
    
    _1_809("1 809"),
    
    _1_868("1 868"),
    
    _1_869("1 869"),
    
    _1_876("1 876"),
    
    _1("1"),
    
    _20("20"),
    
    _212("212"),
    
    _213("213"),
    
    _216("216"),
    
    _218("218"),
    
    _220("220"),
    
    _221("221"),
    
    _222("222"),
    
    _223("223"),
    
    _224("224"),
    
    _225("225"),
    
    _226("226"),
    
    _227("227"),
    
    _228("228"),
    
    _229("229"),
    
    _230("230"),
    
    _231("231"),
    
    _232("232"),
    
    _233("233"),
    
    _234("234"),
    
    _235("235"),
    
    _236("236"),
    
    _237("237"),
    
    _238("238"),
    
    _239("239"),
    
    _240("240"),
    
    _241("241"),
    
    _242("242"),
    
    _243("243"),
    
    _244("244"),
    
    _245("245"),
    
    _248("248"),
    
    _249("249"),
    
    _250("250"),
    
    _251("251"),
    
    _252("252"),
    
    _253("253"),
    
    _254("254"),
    
    _255("255"),
    
    _256("256"),
    
    _257("257"),
    
    _258("258"),
    
    _260("260"),
    
    _261("261"),
    
    _262("262"),
    
    _263("263"),
    
    _264("264"),
    
    _265("265"),
    
    _266("266"),
    
    _267("267"),
    
    _268("268"),
    
    _269("269"),
    
    _27("27"),
    
    _290("290"),
    
    _291("291"),
    
    _297("297"),
    
    _298("298"),
    
    _299("299"),
    
    _30("30"),
    
    _31("31"),
    
    _32("32"),
    
    _33("33"),
    
    _34("34"),
    
    _350("350"),
    
    _351("351"),
    
    _352("352"),
    
    _353("353"),
    
    _354("354"),
    
    _355("355"),
    
    _356("356"),
    
    _357("357"),
    
    _358("358"),
    
    _359("359"),
    
    _36("36"),
    
    _370("370"),
    
    _371("371"),
    
    _372("372"),
    
    _373("373"),
    
    _374("374"),
    
    _375("375"),
    
    _376("376"),
    
    _377("377"),
    
    _378("378"),
    
    _380("380"),
    
    _381("381"),
    
    _382("382"),
    
    _385("385"),
    
    _386("386"),
    
    _387("387"),
    
    _389("389"),
    
    _39("39"),
    
    _40("40"),
    
    _41("41"),
    
    _420("420"),
    
    _421("421"),
    
    _423("423"),
    
    _43("43"),
    
    _44("44"),
    
    _45("45"),
    
    _46("46"),
    
    _47("47"),
    
    _48("48"),
    
    _49("49"),
    
    _500("500"),
    
    _501("501"),
    
    _502("502"),
    
    _503("503"),
    
    _504("504"),
    
    _505("505"),
    
    _506("506"),
    
    _507("507"),
    
    _508("508"),
    
    _509("509"),
    
    _51("51"),
    
    _52("52"),
    
    _53("53"),
    
    _54("54"),
    
    _55("55"),
    
    _56("56"),
    
    _57("57"),
    
    _58("58"),
    
    _590("590"),
    
    _591("591"),
    
    _592("592"),
    
    _593("593"),
    
    _595("595"),
    
    _597("597"),
    
    _598("598"),
    
    _599("599"),
    
    _60("60"),
    
    _61("61"),
    
    _62("62"),
    
    _63("63"),
    
    _64("64"),
    
    _65("65"),
    
    _66("66"),
    
    _670("670"),
    
    _672("672"),
    
    _673("673"),
    
    _674("674"),
    
    _675("675"),
    
    _676("676"),
    
    _677("677"),
    
    _678("678"),
    
    _679("679"),
    
    _680("680"),
    
    _681("681"),
    
    _682("682"),
    
    _683("683"),
    
    _685("685"),
    
    _686("686"),
    
    _687("687"),
    
    _688("688"),
    
    _689("689"),
    
    _690("690"),
    
    _691("691"),
    
    _692("692"),
    
    _7("7"),
    
    _81("81"),
    
    _82("82"),
    
    _84("84"),
    
    _850("850"),
    
    _852("852"),
    
    _853("853"),
    
    _855("855"),
    
    _856("856"),
    
    _86("86"),
    
    _870("870"),
    
    _880("880"),
    
    _886("886"),
    
    _90("90"),
    
    _91("91"),
    
    _92("92"),
    
    _93("93"),
    
    _94("94"),
    
    _95("95"),
    
    _960("960"),
    
    _961("961"),
    
    _962("962"),
    
    _963("963"),
    
    _964("964"),
    
    _965("965"),
    
    _966("966"),
    
    _967("967"),
    
    _968("968"),
    
    _970("970"),
    
    _971("971"),
    
    _972("972"),
    
    _973("973"),
    
    _974("974"),
    
    _975("975"),
    
    _976("976"),
    
    _977("977"),
    
    _98("98"),
    
    _992("992"),
    
    _993("993"),
    
    _994("994"),
    
    _995("995"),
    
    _996("996"),
    
    _998("998");

    private String value;

    ValueEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValueEnum fromValue(String text) {
      for (ValueEnum b : ValueEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("value")
  private ValueEnum value = null;

  public EnumPtyTlcCntryPhoneCd value(ValueEnum value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public ValueEnum getValue() {
    return value;
  }

  public void setValue(ValueEnum value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnumPtyTlcCntryPhoneCd enumPtyTlcCntryPhoneCd = (EnumPtyTlcCntryPhoneCd) o;
    return Objects.equals(this.value, enumPtyTlcCntryPhoneCd.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnumPtyTlcCntryPhoneCd {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

