/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * EnumProvCntryStd
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class EnumProvCntryStd {
  /**
   * Gets or Sets value
   */
  public enum ValueEnum {
    CA_AB("CA-AB"),
    
    CA_BC("CA-BC"),
    
    CA_MB("CA-MB"),
    
    CA_NB("CA-NB"),
    
    CA_NL("CA-NL"),
    
    CA_NS("CA-NS"),
    
    CA_NT("CA-NT"),
    
    CA_NU("CA-NU"),
    
    CA_ON("CA-ON"),
    
    CA_PE("CA-PE"),
    
    CA_QC("CA-QC"),
    
    CA_SK("CA-SK"),
    
    CA_YT("CA-YT"),
    
    INCONNU("INCONNU"),
    
    N_A("N/A"),
    
    US_AK("US-AK"),
    
    US_AL("US-AL"),
    
    US_AR("US-AR"),
    
    US_AS("US-AS"),
    
    US_AZ("US-AZ"),
    
    US_CA("US-CA"),
    
    US_CO("US-CO"),
    
    US_CT("US-CT"),
    
    US_DC("US-DC"),
    
    US_DE("US-DE"),
    
    US_FL("US-FL"),
    
    US_GA("US-GA"),
    
    US_GU("US-GU"),
    
    US_HI("US-HI"),
    
    US_IA("US-IA"),
    
    US_ID("US-ID"),
    
    US_IL("US-IL"),
    
    US_IN("US-IN"),
    
    US_KS("US-KS"),
    
    US_KY("US-KY"),
    
    US_LA("US-LA"),
    
    US_MA("US-MA"),
    
    US_MD("US-MD"),
    
    US_ME("US-ME"),
    
    US_MI("US-MI"),
    
    US_MN("US-MN"),
    
    US_MO("US-MO"),
    
    US_MP("US-MP"),
    
    US_MS("US-MS"),
    
    US_MT("US-MT"),
    
    US_NC("US-NC"),
    
    US_ND("US-ND"),
    
    US_NE("US-NE"),
    
    US_NH("US-NH"),
    
    US_NJ("US-NJ"),
    
    US_NM("US-NM"),
    
    US_NV("US-NV"),
    
    US_NY("US-NY"),
    
    US_OH("US-OH"),
    
    US_OK("US-OK"),
    
    US_OR("US-OR"),
    
    US_PA("US-PA"),
    
    US_PR("US-PR"),
    
    US_RI("US-RI"),
    
    US_SC("US-SC"),
    
    US_SD("US-SD"),
    
    US_TN("US-TN"),
    
    US_TX("US-TX"),
    
    US_UM("US-UM"),
    
    US_UT("US-UT"),
    
    US_VA("US-VA"),
    
    US_VI("US-VI"),
    
    US_VT("US-VT"),
    
    US_WA("US-WA"),
    
    US_WI("US-WI"),
    
    US_WV("US-WV"),
    
    US_WY("US-WY"),
    
    ZZ_ZZ("ZZ-ZZ");

    private String value;

    ValueEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValueEnum fromValue(String text) {
      for (ValueEnum b : ValueEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("value")
  private ValueEnum value = null;

  public EnumProvCntryStd value(ValueEnum value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public ValueEnum getValue() {
    return value;
  }

  public void setValue(ValueEnum value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnumProvCntryStd enumProvCntryStd = (EnumProvCntryStd) o;
    return Objects.equals(this.value, enumProvCntryStd.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnumProvCntryStd {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

