/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.bnc.spti.rbo.dealer.model.DealerType;
import com.bnc.spti.rbo.dealer.model.Message;
import com.bnc.spti.rbo.dealer.model.Response;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * GetDealerStructureResponseType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class GetDealerStructureResponseType {
  @JsonProperty("sessionId")
  private String sessionId = null;

  @JsonProperty("messages")
  private List<Message> messages = null;

  @JsonProperty("dealers")
  private List<DealerType> dealers = new ArrayList<DealerType>();

  public GetDealerStructureResponseType sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  @ApiModelProperty(value = "")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public GetDealerStructureResponseType messages(List<Message> messages) {
    this.messages = messages;
    return this;
  }

  public GetDealerStructureResponseType addMessagesItem(Message messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<Message>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @ApiModelProperty(value = "")
  public List<Message> getMessages() {
    return messages;
  }

  public void setMessages(List<Message> messages) {
    this.messages = messages;
  }

  public GetDealerStructureResponseType dealers(List<DealerType> dealers) {
    this.dealers = dealers;
    return this;
  }

  public GetDealerStructureResponseType addDealersItem(DealerType dealersItem) {
    this.dealers.add(dealersItem);
    return this;
  }

   /**
   * Get dealers
   * @return dealers
  **/
  @ApiModelProperty(required = true, value = "")
  public List<DealerType> getDealers() {
    return dealers;
  }

  public void setDealers(List<DealerType> dealers) {
    this.dealers = dealers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDealerStructureResponseType getDealerStructureResponseType = (GetDealerStructureResponseType) o;
    return Objects.equals(this.sessionId, getDealerStructureResponseType.sessionId) &&
        Objects.equals(this.messages, getDealerStructureResponseType.messages) &&
        Objects.equals(this.dealers, getDealerStructureResponseType.dealers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionId, messages, dealers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDealerStructureResponseType {\n");
    
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    dealers: ").append(toIndentedString(dealers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

