/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * IndividualNameType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class IndividualNameType {
  @JsonProperty("givenName")
  private String givenName = null;

  @JsonProperty("individualNmTitleCd")
  private String individualNmTitleCd = null;

  @JsonProperty("middleName")
  private String middleName = null;

  @JsonProperty("surname")
  private String surname = null;

  @JsonProperty("shortName")
  private String shortName = null;

  public IndividualNameType givenName(String givenName) {
    this.givenName = givenName;
    return this;
  }

   /**
   * Get givenName
   * @return givenName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getGivenName() {
    return givenName;
  }

  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }

  public IndividualNameType individualNmTitleCd(String individualNmTitleCd) {
    this.individualNmTitleCd = individualNmTitleCd;
    return this;
  }

   /**
   * Get individualNmTitleCd
   * @return individualNmTitleCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getIndividualNmTitleCd() {
    return individualNmTitleCd;
  }

  public void setIndividualNmTitleCd(String individualNmTitleCd) {
    this.individualNmTitleCd = individualNmTitleCd;
  }

  public IndividualNameType middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public IndividualNameType surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * Get surname
   * @return surname
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public IndividualNameType shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
  @ApiModelProperty(value = "")
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndividualNameType individualNameType = (IndividualNameType) o;
    return Objects.equals(this.givenName, individualNameType.givenName) &&
        Objects.equals(this.individualNmTitleCd, individualNameType.individualNmTitleCd) &&
        Objects.equals(this.middleName, individualNameType.middleName) &&
        Objects.equals(this.surname, individualNameType.surname) &&
        Objects.equals(this.shortName, individualNameType.shortName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(givenName, individualNmTitleCd, middleName, surname, shortName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualNameType {\n");
    
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    individualNmTitleCd: ").append(toIndentedString(individualNmTitleCd)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

