/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.bnc.spti.rbo.dealer.model.Description;
import com.bnc.spti.rbo.dealer.model.EnumOrgHomeJurisdGeoAreaCd;
import com.bnc.spti.rbo.dealer.model.PartyAddressType;
import com.bnc.spti.rbo.dealer.model.PartyType;
import com.bnc.spti.rbo.dealer.model.PtyElectronicCtcInfoType;
import com.bnc.spti.rbo.dealer.model.PtyTelecommunicationType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * OrganizationType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class OrganizationType {
  @JsonProperty("partyAddresses")
  private List<PartyAddressType> partyAddresses = new ArrayList<PartyAddressType>();

  @JsonProperty("ptyElectronicCtcInfos")
  private List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos = new ArrayList<PtyElectronicCtcInfoType>();

  @JsonProperty("ptyTelecommunications")
  private List<PtyTelecommunicationType> ptyTelecommunications = new ArrayList<PtyTelecommunicationType>();

  @JsonProperty("orgConstitutionDt")
  private Date orgConstitutionDt = null;

  @JsonProperty("orgDtFiscalYearEndDay")
  private Integer orgDtFiscalYearEndDay = null;

  @JsonProperty("orgDtFiscalYearEndMth")
  private Integer orgDtFiscalYearEndMth = null;

  @JsonProperty("orgHomeJurisdGeoAreaCd")
  private EnumOrgHomeJurisdGeoAreaCd orgHomeJurisdGeoAreaCd = null;

  @JsonProperty("orgHomeJurisdGeoAreaTypeCd")
  private String orgHomeJurisdGeoAreaTypeCd = null;

  @JsonProperty("orgLglFormCd")
  private String orgLglFormCd = null;

  @JsonProperty("orgLglFormTypeCd")
  private String orgLglFormTypeCd = null;

  @JsonProperty("organizationName")
  private Description organizationName = null;

  public OrganizationType partyAddresses(List<PartyAddressType> partyAddresses) {
    this.partyAddresses = partyAddresses;
    return this;
  }

  public OrganizationType addPartyAddressesItem(PartyAddressType partyAddressesItem) {
    this.partyAddresses.add(partyAddressesItem);
    return this;
  }

   /**
   * Get partyAddresses
   * @return partyAddresses
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PartyAddressType> getPartyAddresses() {
    return partyAddresses;
  }

  public void setPartyAddresses(List<PartyAddressType> partyAddresses) {
    this.partyAddresses = partyAddresses;
  }

  public OrganizationType ptyElectronicCtcInfos(List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos) {
    this.ptyElectronicCtcInfos = ptyElectronicCtcInfos;
    return this;
  }

  public OrganizationType addPtyElectronicCtcInfosItem(PtyElectronicCtcInfoType ptyElectronicCtcInfosItem) {
    this.ptyElectronicCtcInfos.add(ptyElectronicCtcInfosItem);
    return this;
  }

   /**
   * Get ptyElectronicCtcInfos
   * @return ptyElectronicCtcInfos
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PtyElectronicCtcInfoType> getPtyElectronicCtcInfos() {
    return ptyElectronicCtcInfos;
  }

  public void setPtyElectronicCtcInfos(List<PtyElectronicCtcInfoType> ptyElectronicCtcInfos) {
    this.ptyElectronicCtcInfos = ptyElectronicCtcInfos;
  }

  public OrganizationType ptyTelecommunications(List<PtyTelecommunicationType> ptyTelecommunications) {
    this.ptyTelecommunications = ptyTelecommunications;
    return this;
  }

  public OrganizationType addPtyTelecommunicationsItem(PtyTelecommunicationType ptyTelecommunicationsItem) {
    this.ptyTelecommunications.add(ptyTelecommunicationsItem);
    return this;
  }

   /**
   * Get ptyTelecommunications
   * @return ptyTelecommunications
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PtyTelecommunicationType> getPtyTelecommunications() {
    return ptyTelecommunications;
  }

  public void setPtyTelecommunications(List<PtyTelecommunicationType> ptyTelecommunications) {
    this.ptyTelecommunications = ptyTelecommunications;
  }

  public OrganizationType orgConstitutionDt(Date orgConstitutionDt) {
    this.orgConstitutionDt = orgConstitutionDt;
    return this;
  }

   /**
   * Get orgConstitutionDt
   * @return orgConstitutionDt
  **/
  @ApiModelProperty(required = true, value = "")
  public Date getOrgConstitutionDt() {
    return orgConstitutionDt;
  }

  public void setOrgConstitutionDt(Date orgConstitutionDt) {
    this.orgConstitutionDt = orgConstitutionDt;
  }

  public OrganizationType orgDtFiscalYearEndDay(Integer orgDtFiscalYearEndDay) {
    this.orgDtFiscalYearEndDay = orgDtFiscalYearEndDay;
    return this;
  }

   /**
   * Get orgDtFiscalYearEndDay
   * @return orgDtFiscalYearEndDay
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrgDtFiscalYearEndDay() {
    return orgDtFiscalYearEndDay;
  }

  public void setOrgDtFiscalYearEndDay(Integer orgDtFiscalYearEndDay) {
    this.orgDtFiscalYearEndDay = orgDtFiscalYearEndDay;
  }

  public OrganizationType orgDtFiscalYearEndMth(Integer orgDtFiscalYearEndMth) {
    this.orgDtFiscalYearEndMth = orgDtFiscalYearEndMth;
    return this;
  }

   /**
   * Get orgDtFiscalYearEndMth
   * @return orgDtFiscalYearEndMth
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrgDtFiscalYearEndMth() {
    return orgDtFiscalYearEndMth;
  }

  public void setOrgDtFiscalYearEndMth(Integer orgDtFiscalYearEndMth) {
    this.orgDtFiscalYearEndMth = orgDtFiscalYearEndMth;
  }

  public OrganizationType orgHomeJurisdGeoAreaCd(EnumOrgHomeJurisdGeoAreaCd orgHomeJurisdGeoAreaCd) {
    this.orgHomeJurisdGeoAreaCd = orgHomeJurisdGeoAreaCd;
    return this;
  }

   /**
   * Get orgHomeJurisdGeoAreaCd
   * @return orgHomeJurisdGeoAreaCd
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumOrgHomeJurisdGeoAreaCd getOrgHomeJurisdGeoAreaCd() {
    return orgHomeJurisdGeoAreaCd;
  }

  public void setOrgHomeJurisdGeoAreaCd(EnumOrgHomeJurisdGeoAreaCd orgHomeJurisdGeoAreaCd) {
    this.orgHomeJurisdGeoAreaCd = orgHomeJurisdGeoAreaCd;
  }

  public OrganizationType orgHomeJurisdGeoAreaTypeCd(String orgHomeJurisdGeoAreaTypeCd) {
    this.orgHomeJurisdGeoAreaTypeCd = orgHomeJurisdGeoAreaTypeCd;
    return this;
  }

   /**
   * Get orgHomeJurisdGeoAreaTypeCd
   * @return orgHomeJurisdGeoAreaTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgHomeJurisdGeoAreaTypeCd() {
    return orgHomeJurisdGeoAreaTypeCd;
  }

  public void setOrgHomeJurisdGeoAreaTypeCd(String orgHomeJurisdGeoAreaTypeCd) {
    this.orgHomeJurisdGeoAreaTypeCd = orgHomeJurisdGeoAreaTypeCd;
  }

  public OrganizationType orgLglFormCd(String orgLglFormCd) {
    this.orgLglFormCd = orgLglFormCd;
    return this;
  }

   /**
   * Get orgLglFormCd
   * @return orgLglFormCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgLglFormCd() {
    return orgLglFormCd;
  }

  public void setOrgLglFormCd(String orgLglFormCd) {
    this.orgLglFormCd = orgLglFormCd;
  }

  public OrganizationType orgLglFormTypeCd(String orgLglFormTypeCd) {
    this.orgLglFormTypeCd = orgLglFormTypeCd;
    return this;
  }

   /**
   * Get orgLglFormTypeCd
   * @return orgLglFormTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrgLglFormTypeCd() {
    return orgLglFormTypeCd;
  }

  public void setOrgLglFormTypeCd(String orgLglFormTypeCd) {
    this.orgLglFormTypeCd = orgLglFormTypeCd;
  }

  public OrganizationType organizationName(Description organizationName) {
    this.organizationName = organizationName;
    return this;
  }

   /**
   * Get organizationName
   * @return organizationName
  **/
  @ApiModelProperty(required = true, value = "")
  public Description getOrganizationName() {
    return organizationName;
  }

  public void setOrganizationName(Description organizationName) {
    this.organizationName = organizationName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationType organizationType = (OrganizationType) o;
    return Objects.equals(this.partyAddresses, organizationType.partyAddresses) &&
        Objects.equals(this.ptyElectronicCtcInfos, organizationType.ptyElectronicCtcInfos) &&
        Objects.equals(this.ptyTelecommunications, organizationType.ptyTelecommunications) &&
        Objects.equals(this.orgConstitutionDt, organizationType.orgConstitutionDt) &&
        Objects.equals(this.orgDtFiscalYearEndDay, organizationType.orgDtFiscalYearEndDay) &&
        Objects.equals(this.orgDtFiscalYearEndMth, organizationType.orgDtFiscalYearEndMth) &&
        Objects.equals(this.orgHomeJurisdGeoAreaCd, organizationType.orgHomeJurisdGeoAreaCd) &&
        Objects.equals(this.orgHomeJurisdGeoAreaTypeCd, organizationType.orgHomeJurisdGeoAreaTypeCd) &&
        Objects.equals(this.orgLglFormCd, organizationType.orgLglFormCd) &&
        Objects.equals(this.orgLglFormTypeCd, organizationType.orgLglFormTypeCd) &&
        Objects.equals(this.organizationName, organizationType.organizationName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyAddresses, ptyElectronicCtcInfos, ptyTelecommunications, orgConstitutionDt, orgDtFiscalYearEndDay, orgDtFiscalYearEndMth, orgHomeJurisdGeoAreaCd, orgHomeJurisdGeoAreaTypeCd, orgLglFormCd, orgLglFormTypeCd, organizationName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationType {\n");
    
    sb.append("    partyAddresses: ").append(toIndentedString(partyAddresses)).append("\n");
    sb.append("    ptyElectronicCtcInfos: ").append(toIndentedString(ptyElectronicCtcInfos)).append("\n");
    sb.append("    ptyTelecommunications: ").append(toIndentedString(ptyTelecommunications)).append("\n");
    sb.append("    orgConstitutionDt: ").append(toIndentedString(orgConstitutionDt)).append("\n");
    sb.append("    orgDtFiscalYearEndDay: ").append(toIndentedString(orgDtFiscalYearEndDay)).append("\n");
    sb.append("    orgDtFiscalYearEndMth: ").append(toIndentedString(orgDtFiscalYearEndMth)).append("\n");
    sb.append("    orgHomeJurisdGeoAreaCd: ").append(toIndentedString(orgHomeJurisdGeoAreaCd)).append("\n");
    sb.append("    orgHomeJurisdGeoAreaTypeCd: ").append(toIndentedString(orgHomeJurisdGeoAreaTypeCd)).append("\n");
    sb.append("    orgLglFormCd: ").append(toIndentedString(orgLglFormCd)).append("\n");
    sb.append("    orgLglFormTypeCd: ").append(toIndentedString(orgLglFormTypeCd)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

