/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.bnc.spti.rbo.dealer.model.AddressType;
import com.bnc.spti.rbo.dealer.model.EnumPtyAddrUsageCd;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PartyAddressType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class PartyAddressType {
  @JsonProperty("addressType")
  private AddressType addressType = null;

  @JsonProperty("ptyAddrUsageTypeCd")
  private EnumPtyAddrUsageCd ptyAddrUsageTypeCd = null;

  public PartyAddressType addressType(AddressType addressType) {
    this.addressType = addressType;
    return this;
  }

   /**
   * Get addressType
   * @return addressType
  **/
  @ApiModelProperty(required = true, value = "")
  public AddressType getAddressType() {
    return addressType;
  }

  public void setAddressType(AddressType addressType) {
    this.addressType = addressType;
  }

  public PartyAddressType ptyAddrUsageTypeCd(EnumPtyAddrUsageCd ptyAddrUsageTypeCd) {
    this.ptyAddrUsageTypeCd = ptyAddrUsageTypeCd;
    return this;
  }

   /**
   * Get ptyAddrUsageTypeCd
   * @return ptyAddrUsageTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumPtyAddrUsageCd getPtyAddrUsageTypeCd() {
    return ptyAddrUsageTypeCd;
  }

  public void setPtyAddrUsageTypeCd(EnumPtyAddrUsageCd ptyAddrUsageTypeCd) {
    this.ptyAddrUsageTypeCd = ptyAddrUsageTypeCd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartyAddressType partyAddressType = (PartyAddressType) o;
    return Objects.equals(this.addressType, partyAddressType.addressType) &&
        Objects.equals(this.ptyAddrUsageTypeCd, partyAddressType.ptyAddrUsageTypeCd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressType, ptyAddrUsageTypeCd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartyAddressType {\n");
    
    sb.append("    addressType: ").append(toIndentedString(addressType)).append("\n");
    sb.append("    ptyAddrUsageTypeCd: ").append(toIndentedString(ptyAddrUsageTypeCd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

