/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.bnc.spti.rbo.dealer.model.EnumPtyElectronicCtcInfoMethdUsgTypeCd;
import com.bnc.spti.rbo.dealer.model.EnumPtyElectronicCtcInfoTypeCode;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PtyElectronicCtcInfoType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class PtyElectronicCtcInfoType {
  @JsonProperty("ptyElectronicCtcInfoAddrNm")
  private String ptyElectronicCtcInfoAddrNm = null;

  @JsonProperty("ptyElectronicCtcInfoMethdUsgTypeCd")
  private EnumPtyElectronicCtcInfoMethdUsgTypeCd ptyElectronicCtcInfoMethdUsgTypeCd = null;

  @JsonProperty("ptyElectronicCtcInfoTypeCode")
  private EnumPtyElectronicCtcInfoTypeCode ptyElectronicCtcInfoTypeCode = null;

  public PtyElectronicCtcInfoType ptyElectronicCtcInfoAddrNm(String ptyElectronicCtcInfoAddrNm) {
    this.ptyElectronicCtcInfoAddrNm = ptyElectronicCtcInfoAddrNm;
    return this;
  }

   /**
   * Get ptyElectronicCtcInfoAddrNm
   * @return ptyElectronicCtcInfoAddrNm
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPtyElectronicCtcInfoAddrNm() {
    return ptyElectronicCtcInfoAddrNm;
  }

  public void setPtyElectronicCtcInfoAddrNm(String ptyElectronicCtcInfoAddrNm) {
    this.ptyElectronicCtcInfoAddrNm = ptyElectronicCtcInfoAddrNm;
  }

  public PtyElectronicCtcInfoType ptyElectronicCtcInfoMethdUsgTypeCd(EnumPtyElectronicCtcInfoMethdUsgTypeCd ptyElectronicCtcInfoMethdUsgTypeCd) {
    this.ptyElectronicCtcInfoMethdUsgTypeCd = ptyElectronicCtcInfoMethdUsgTypeCd;
    return this;
  }

   /**
   * Get ptyElectronicCtcInfoMethdUsgTypeCd
   * @return ptyElectronicCtcInfoMethdUsgTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumPtyElectronicCtcInfoMethdUsgTypeCd getPtyElectronicCtcInfoMethdUsgTypeCd() {
    return ptyElectronicCtcInfoMethdUsgTypeCd;
  }

  public void setPtyElectronicCtcInfoMethdUsgTypeCd(EnumPtyElectronicCtcInfoMethdUsgTypeCd ptyElectronicCtcInfoMethdUsgTypeCd) {
    this.ptyElectronicCtcInfoMethdUsgTypeCd = ptyElectronicCtcInfoMethdUsgTypeCd;
  }

  public PtyElectronicCtcInfoType ptyElectronicCtcInfoTypeCode(EnumPtyElectronicCtcInfoTypeCode ptyElectronicCtcInfoTypeCode) {
    this.ptyElectronicCtcInfoTypeCode = ptyElectronicCtcInfoTypeCode;
    return this;
  }

   /**
   * Get ptyElectronicCtcInfoTypeCode
   * @return ptyElectronicCtcInfoTypeCode
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumPtyElectronicCtcInfoTypeCode getPtyElectronicCtcInfoTypeCode() {
    return ptyElectronicCtcInfoTypeCode;
  }

  public void setPtyElectronicCtcInfoTypeCode(EnumPtyElectronicCtcInfoTypeCode ptyElectronicCtcInfoTypeCode) {
    this.ptyElectronicCtcInfoTypeCode = ptyElectronicCtcInfoTypeCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PtyElectronicCtcInfoType ptyElectronicCtcInfoType = (PtyElectronicCtcInfoType) o;
    return Objects.equals(this.ptyElectronicCtcInfoAddrNm, ptyElectronicCtcInfoType.ptyElectronicCtcInfoAddrNm) &&
        Objects.equals(this.ptyElectronicCtcInfoMethdUsgTypeCd, ptyElectronicCtcInfoType.ptyElectronicCtcInfoMethdUsgTypeCd) &&
        Objects.equals(this.ptyElectronicCtcInfoTypeCode, ptyElectronicCtcInfoType.ptyElectronicCtcInfoTypeCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ptyElectronicCtcInfoAddrNm, ptyElectronicCtcInfoMethdUsgTypeCd, ptyElectronicCtcInfoTypeCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PtyElectronicCtcInfoType {\n");
    
    sb.append("    ptyElectronicCtcInfoAddrNm: ").append(toIndentedString(ptyElectronicCtcInfoAddrNm)).append("\n");
    sb.append("    ptyElectronicCtcInfoMethdUsgTypeCd: ").append(toIndentedString(ptyElectronicCtcInfoMethdUsgTypeCd)).append("\n");
    sb.append("    ptyElectronicCtcInfoTypeCode: ").append(toIndentedString(ptyElectronicCtcInfoTypeCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

