/*
 * Dealer Structure
 * All Barnchs, Advisors related to a specific dealer 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.dealer.model;

import java.util.Objects;
import com.bnc.spti.rbo.dealer.model.EnumPtyTlcCntryPhoneCd;
import com.bnc.spti.rbo.dealer.model.EnumPtyTlcContactMethdUsgCd;
import com.bnc.spti.rbo.dealer.model.EnumPtyTlcDvcTypeCd;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PtyTelecommunicationType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-11T09:20:13.171-05:00")
public class PtyTelecommunicationType {
  @JsonProperty("ptyTlcAreaPhoneCd")
  private Integer ptyTlcAreaPhoneCd = null;

  @JsonProperty("ptyTlcCntryPhoneCd")
  private EnumPtyTlcCntryPhoneCd ptyTlcCntryPhoneCd = null;

  @JsonProperty("ptyTlcCompletePhoneNo")
  private Integer ptyTlcCompletePhoneNo = null;

  @JsonProperty("ptyTlcContactMethdUsgTypeCd")
  private EnumPtyTlcContactMethdUsgCd ptyTlcContactMethdUsgTypeCd = null;

  @JsonProperty("ptyTlcDvcTypeCd")
  private EnumPtyTlcDvcTypeCd ptyTlcDvcTypeCd = null;

  @JsonProperty("ptyTlcExtension")
  private Integer ptyTlcExtension = null;

  @JsonProperty("ptyTlcLocalNo")
  private Integer ptyTlcLocalNo = null;

  public PtyTelecommunicationType ptyTlcAreaPhoneCd(Integer ptyTlcAreaPhoneCd) {
    this.ptyTlcAreaPhoneCd = ptyTlcAreaPhoneCd;
    return this;
  }

   /**
   * Get ptyTlcAreaPhoneCd
   * @return ptyTlcAreaPhoneCd
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPtyTlcAreaPhoneCd() {
    return ptyTlcAreaPhoneCd;
  }

  public void setPtyTlcAreaPhoneCd(Integer ptyTlcAreaPhoneCd) {
    this.ptyTlcAreaPhoneCd = ptyTlcAreaPhoneCd;
  }

  public PtyTelecommunicationType ptyTlcCntryPhoneCd(EnumPtyTlcCntryPhoneCd ptyTlcCntryPhoneCd) {
    this.ptyTlcCntryPhoneCd = ptyTlcCntryPhoneCd;
    return this;
  }

   /**
   * Get ptyTlcCntryPhoneCd
   * @return ptyTlcCntryPhoneCd
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumPtyTlcCntryPhoneCd getPtyTlcCntryPhoneCd() {
    return ptyTlcCntryPhoneCd;
  }

  public void setPtyTlcCntryPhoneCd(EnumPtyTlcCntryPhoneCd ptyTlcCntryPhoneCd) {
    this.ptyTlcCntryPhoneCd = ptyTlcCntryPhoneCd;
  }

  public PtyTelecommunicationType ptyTlcCompletePhoneNo(Integer ptyTlcCompletePhoneNo) {
    this.ptyTlcCompletePhoneNo = ptyTlcCompletePhoneNo;
    return this;
  }

   /**
   * Get ptyTlcCompletePhoneNo
   * @return ptyTlcCompletePhoneNo
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPtyTlcCompletePhoneNo() {
    return ptyTlcCompletePhoneNo;
  }

  public void setPtyTlcCompletePhoneNo(Integer ptyTlcCompletePhoneNo) {
    this.ptyTlcCompletePhoneNo = ptyTlcCompletePhoneNo;
  }

  public PtyTelecommunicationType ptyTlcContactMethdUsgTypeCd(EnumPtyTlcContactMethdUsgCd ptyTlcContactMethdUsgTypeCd) {
    this.ptyTlcContactMethdUsgTypeCd = ptyTlcContactMethdUsgTypeCd;
    return this;
  }

   /**
   * Get ptyTlcContactMethdUsgTypeCd
   * @return ptyTlcContactMethdUsgTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumPtyTlcContactMethdUsgCd getPtyTlcContactMethdUsgTypeCd() {
    return ptyTlcContactMethdUsgTypeCd;
  }

  public void setPtyTlcContactMethdUsgTypeCd(EnumPtyTlcContactMethdUsgCd ptyTlcContactMethdUsgTypeCd) {
    this.ptyTlcContactMethdUsgTypeCd = ptyTlcContactMethdUsgTypeCd;
  }

  public PtyTelecommunicationType ptyTlcDvcTypeCd(EnumPtyTlcDvcTypeCd ptyTlcDvcTypeCd) {
    this.ptyTlcDvcTypeCd = ptyTlcDvcTypeCd;
    return this;
  }

   /**
   * Get ptyTlcDvcTypeCd
   * @return ptyTlcDvcTypeCd
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumPtyTlcDvcTypeCd getPtyTlcDvcTypeCd() {
    return ptyTlcDvcTypeCd;
  }

  public void setPtyTlcDvcTypeCd(EnumPtyTlcDvcTypeCd ptyTlcDvcTypeCd) {
    this.ptyTlcDvcTypeCd = ptyTlcDvcTypeCd;
  }

  public PtyTelecommunicationType ptyTlcExtension(Integer ptyTlcExtension) {
    this.ptyTlcExtension = ptyTlcExtension;
    return this;
  }

   /**
   * Get ptyTlcExtension
   * @return ptyTlcExtension
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPtyTlcExtension() {
    return ptyTlcExtension;
  }

  public void setPtyTlcExtension(Integer ptyTlcExtension) {
    this.ptyTlcExtension = ptyTlcExtension;
  }

  public PtyTelecommunicationType ptyTlcLocalNo(Integer ptyTlcLocalNo) {
    this.ptyTlcLocalNo = ptyTlcLocalNo;
    return this;
  }

   /**
   * Get ptyTlcLocalNo
   * @return ptyTlcLocalNo
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPtyTlcLocalNo() {
    return ptyTlcLocalNo;
  }

  public void setPtyTlcLocalNo(Integer ptyTlcLocalNo) {
    this.ptyTlcLocalNo = ptyTlcLocalNo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PtyTelecommunicationType ptyTelecommunicationType = (PtyTelecommunicationType) o;
    return Objects.equals(this.ptyTlcAreaPhoneCd, ptyTelecommunicationType.ptyTlcAreaPhoneCd) &&
        Objects.equals(this.ptyTlcCntryPhoneCd, ptyTelecommunicationType.ptyTlcCntryPhoneCd) &&
        Objects.equals(this.ptyTlcCompletePhoneNo, ptyTelecommunicationType.ptyTlcCompletePhoneNo) &&
        Objects.equals(this.ptyTlcContactMethdUsgTypeCd, ptyTelecommunicationType.ptyTlcContactMethdUsgTypeCd) &&
        Objects.equals(this.ptyTlcDvcTypeCd, ptyTelecommunicationType.ptyTlcDvcTypeCd) &&
        Objects.equals(this.ptyTlcExtension, ptyTelecommunicationType.ptyTlcExtension) &&
        Objects.equals(this.ptyTlcLocalNo, ptyTelecommunicationType.ptyTlcLocalNo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ptyTlcAreaPhoneCd, ptyTlcCntryPhoneCd, ptyTlcCompletePhoneNo, ptyTlcContactMethdUsgTypeCd, ptyTlcDvcTypeCd, ptyTlcExtension, ptyTlcLocalNo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PtyTelecommunicationType {\n");
    
    sb.append("    ptyTlcAreaPhoneCd: ").append(toIndentedString(ptyTlcAreaPhoneCd)).append("\n");
    sb.append("    ptyTlcCntryPhoneCd: ").append(toIndentedString(ptyTlcCntryPhoneCd)).append("\n");
    sb.append("    ptyTlcCompletePhoneNo: ").append(toIndentedString(ptyTlcCompletePhoneNo)).append("\n");
    sb.append("    ptyTlcContactMethdUsgTypeCd: ").append(toIndentedString(ptyTlcContactMethdUsgTypeCd)).append("\n");
    sb.append("    ptyTlcDvcTypeCd: ").append(toIndentedString(ptyTlcDvcTypeCd)).append("\n");
    sb.append("    ptyTlcExtension: ").append(toIndentedString(ptyTlcExtension)).append("\n");
    sb.append("    ptyTlcLocalNo: ").append(toIndentedString(ptyTlcLocalNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

