/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * The version of the OpenAPI document: 5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.cogitosum.rdi.api.model.Criteria;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Criteria
 */
public class CriteriaTest {
    private final Criteria model = new Criteria();

    /**
     * Model tests for Criteria
     */
    @Test
    public void testCriteria() {
        // TODO: test Criteria
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'operator'
     */
    @Test
    public void operatorTest() {
        // TODO: test operator
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
