/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * The version of the OpenAPI document: 5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.cogitosum.rdi.api.model.Document;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Document
 */
public class DocumentTest {
    private final Document model = new Document();

    /**
     * Model tests for Document
     */
    @Test
    public void testDocument() {
        // TODO: test Document
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'docId'
     */
    @Test
    public void docIdTest() {
        // TODO: test docId
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
