/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * The version of the OpenAPI document: 5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.cogitosum.rdi.api.model.Field;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Field
 */
public class FieldTest {
    private final Field model = new Field();

    /**
     * Model tests for Field
     */
    @Test
    public void testField() {
        // TODO: test Field
    }

    /**
     * Test the property 'ascending'
     */
    @Test
    public void ascendingTest() {
        // TODO: test ascending
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'sortOrder'
     */
    @Test
    public void sortOrderTest() {
        // TODO: test sortOrder
    }

}
