/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * The version of the OpenAPI document: 5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.cogitosum.rdi.api.model.ModelAndView;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModelAndView
 */
public class ModelAndViewTest {
    private final ModelAndView model = new ModelAndView();

    /**
     * Model tests for ModelAndView
     */
    @Test
    public void testModelAndView() {
        // TODO: test ModelAndView
    }

    /**
     * Test the property 'empty'
     */
    @Test
    public void emptyTest() {
        // TODO: test empty
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'modelMap'
     */
    @Test
    public void modelMapTest() {
        // TODO: test modelMap
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'view'
     */
    @Test
    public void viewTest() {
        // TODO: test view
    }

    /**
     * Test the property 'viewName'
     */
    @Test
    public void viewNameTest() {
        // TODO: test viewName
    }

}
