/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * The version of the OpenAPI document: 5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.cogitosum.rdi.api.model.SearchDetails;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchDetails
 */
public class SearchDetailsTest {
    private final SearchDetails model = new SearchDetails();

    /**
     * Model tests for SearchDetails
     */
    @Test
    public void testSearchDetails() {
        // TODO: test SearchDetails
    }

    /**
     * Test the property 'currentPage'
     */
    @Test
    public void currentPageTest() {
        // TODO: test currentPage
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'totalItem'
     */
    @Test
    public void totalItemTest() {
        // TODO: test totalItem
    }

    /**
     * Test the property 'totalPage'
     */
    @Test
    public void totalPageTest() {
        // TODO: test totalPage
    }

}
