/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * The version of the OpenAPI document: 5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.cogitosum.rdi.api.model.SearchCriteria;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchCriteria
 */
public class SearchCriteriaTest {
    private final SearchCriteria model = new SearchCriteria();

    /**
     * Model tests for SearchCriteria
     */
    @Test
    public void testSearchCriteria() {
        // TODO: test SearchCriteria
    }

    /**
     * Test the property 'criteria'
     */
    @Test
    public void criteriaTest() {
        // TODO: test criteria
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    public void pageNumberTest() {
        // TODO: test pageNumber
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

}
