/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * The version of the OpenAPI document: 5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.cogitosum.rdi.api.model.SearchResult;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchResult
 */
public class SearchResultTest {
    private final SearchResult model = new SearchResult();

    /**
     * Model tests for SearchResult
     */
    @Test
    public void testSearchResult() {
        // TODO: test SearchResult
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property 'searchDetails'
     */
    @Test
    public void searchDetailsTest() {
        // TODO: test searchDetails
    }

}
