/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * The version of the OpenAPI document: 5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.cogitosum.rdi.api.model.URI;
import org.junit.jupiter.api.Test;

/**
 * Model tests for URI
 */
public class URITest {
    private final URI model = new URI();

    /**
     * Model tests for URI
     */
    @Test
    public void testURIC() {
        // TODO: test URI
    }

    /**
     * Test the property 'absolute'
     */
    @Test
    public void absoluteTest() {
        // TODO: test absolute
    }

    /**
     * Test the property 'authority'
     */
    @Test
    public void authorityTest() {
        // TODO: test authority
    }

    /**
     * Test the property 'fragment'
     */
    @Test
    public void fragmentTest() {
        // TODO: test fragment
    }

    /**
     * Test the property 'host'
     */
    @Test
    public void hostTest() {
        // TODO: test host
    }

    /**
     * Test the property 'opaque'
     */
    @Test
    public void opaqueTest() {
        // TODO: test opaque
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'rawAuthority'
     */
    @Test
    public void rawAuthorityTest() {
        // TODO: test rawAuthority
    }

    /**
     * Test the property 'rawFragment'
     */
    @Test
    public void rawFragmentTest() {
        // TODO: test rawFragment
    }

    /**
     * Test the property 'rawPath'
     */
    @Test
    public void rawPathTest() {
        // TODO: test rawPath
    }

    /**
     * Test the property 'rawQuery'
     */
    @Test
    public void rawQueryTest() {
        // TODO: test rawQuery
    }

    /**
     * Test the property 'rawSchemeSpecificPart'
     */
    @Test
    public void rawSchemeSpecificPartTest() {
        // TODO: test rawSchemeSpecificPart
    }

    /**
     * Test the property 'rawUserInfo'
     */
    @Test
    public void rawUserInfoTest() {
        // TODO: test rawUserInfo
    }

    /**
     * Test the property 'scheme'
     */
    @Test
    public void schemeTest() {
        // TODO: test scheme
    }

    /**
     * Test the property 'schemeSpecificPart'
     */
    @Test
    public void schemeSpecificPartTest() {
        // TODO: test schemeSpecificPart
    }

    /**
     * Test the property 'userInfo'
     */
    @Test
    public void userInfoTest() {
        // TODO: test userInfo
    }

}
