/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * The version of the OpenAPI document: 5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.cogitosum.rdi.api.model.URL;
import org.junit.jupiter.api.Test;

/**
 * Model tests for URL
 */
public class URLTest {
    private final URL model = new URL();

    /**
     * Model tests for URL
     */
    @Test
    public void testURL() {
        // TODO: test URL
    }

    /**
     * Test the property 'authority'
     */
    @Test
    public void authorityTest() {
        // TODO: test authority
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'defaultPort'
     */
    @Test
    public void defaultPortTest() {
        // TODO: test defaultPort
    }

    /**
     * Test the property 'deserializedFields'
     */
    @Test
    public void deserializedFieldsTest() {
        // TODO: test deserializedFields
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'host'
     */
    @Test
    public void hostTest() {
        // TODO: test host
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'protocol'
     */
    @Test
    public void protocolTest() {
        // TODO: test protocol
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'ref'
     */
    @Test
    public void refTest() {
        // TODO: test ref
    }

    /**
     * Test the property 'serializedHashCode'
     */
    @Test
    public void serializedHashCodeTest() {
        // TODO: test serializedHashCode
    }

    /**
     * Test the property 'userInfo'
     */
    @Test
    public void userInfoTest() {
        // TODO: test userInfo
    }

}
