/*
 * IAMx oAuth Tokens Management
 * More informations here(https://wiki.bnc.ca/display/IAMAS/IAMx+Documents)
 *
 * OpenAPI spec version: 1.2.5
 * Contact: support.IAM@bnc.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.auth.invoker.auth;

import com.bnc.spti.rbo.auth.invoker.Pair;

import java.util.Map;
import java.util.List;

public interface Authentication {
    /**
     * Apply authentication settings to header and query params.
     *
     * @param queryParams List of query parameters
     * @param headerParams Map of header parameters
     */
    void applyToParams(List<Pair> queryParams, Map<String, String> headerParams);
}
