/*
 * IAMx oAuth Tokens Management
 * More informations here(https://wiki.bnc.ca/display/IAMAS/IAMx+Documents)
 *
 * OpenAPI spec version: 1.2.5
 * Contact: support.IAM@bnc.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.auth.invoker.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
