/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * OpenAPI spec version: 5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.docs.invoker.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
