/*
 * IAMx oAuth Tokens Management
 * More informations here(https://wiki.bnc.ca/display/IAMAS/IAMx+Documents)
 *
 * OpenAPI spec version: 1.2.5
 * Contact: support.IAM@bnc.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.auth.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * IamxTokenResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-22T11:03:19.343-05:00")
public class IamxTokenResponse {
	
	/** Modification Daniel JANS
	 * 28 Novembre 2018
	 * Valeur générée est incorrecte access_token au lieu de accesstoken 
	 */
  @JsonProperty("access_token")
  private String accessToken = null;
  
	/** Modification Daniel JANS
	 * 28 Novembre 2018
	 * Valeur générée est incorrecte type_token au lieu de typetoken 
	 */
  @JsonProperty("token_type")
  private String tokenType = null;

	/** Modification Daniel JANS
	 * 28 Novembre 2018
	 * Valeur générée est incorrecte expires_in au lieu de expiresin 
	 */
  @JsonProperty("expires_in")
  private String expiresIn = null;
  
  /** Modification Daniel JANS
   * 28 Novembre 2018
   * Ajout du scope - Non présent dans le YAML
   * Ne pas oublier les getters et setters ( Voir ci-dessous )
   */
  @JsonProperty("scope")
  private String scope = null;

  public IamxTokenResponse accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * Get accessToken
   * @return accessToken
  **/
  @ApiModelProperty(value = "")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public IamxTokenResponse tokenType(String tokenType) {
    this.tokenType = tokenType;
    return this;
  }

   /**
   * Get tokenType
   * @return tokenType
  **/
  @ApiModelProperty(value = "")
  public String getTokenType() {
    return tokenType;
  }

  public void setTokenType(String tokenType) {
    this.tokenType = tokenType;
  }

  public IamxTokenResponse expiresIn(String expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

   /**
   * Get expiresIn
   * @return expiresIn
  **/
  @ApiModelProperty(value = "")
  public String getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(String expiresIn) {
    this.expiresIn = expiresIn;
  }

  public IamxTokenResponse scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @ApiModelProperty(value = "")
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IamxTokenResponse iamxTokenResponse = (IamxTokenResponse) o;
    return Objects.equals(this.accessToken, iamxTokenResponse.accessToken) &&
        Objects.equals(this.tokenType, iamxTokenResponse.tokenType) &&
        Objects.equals(this.expiresIn, iamxTokenResponse.expiresIn) &&
        Objects.equals(this.scope, iamxTokenResponse.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, tokenType, expiresIn, scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IamxTokenResponse {\n");
    
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    tokenType: ").append(toIndentedString(tokenType)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
