/*
 * IAMx oAuth Tokens Management
 * More informations here(https://wiki.bnc.ca/display/IAMAS/IAMx+Documents)
 *
 * OpenAPI spec version: 1.2.5
 * Contact: support.IAM@bnc.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.auth.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * IamxTokenRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-22T11:03:19.343-05:00")
public class IamxTokenRequest {
  @JsonProperty("grantType")
  private String grantType = null;

  @JsonProperty("redirectUri")
  private String redirectUri = null;

  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("code")
  private String code = null;
  
  // Ajout Daniel JANS - Ajout du scope
  
  @JsonProperty("scope")
  private String scope = null;

  @JsonProperty("codeVerifier")
  private String codeVerifier = null;

  public IamxTokenRequest grantType(String grantType) {
    this.grantType = grantType;
    return this;
  }

   /**
   * Get grantType
   * @return grantType
  **/
  @ApiModelProperty(value = "")
  public String getGrantType() {
    return grantType;
  }

  public void setGrantType(String grantType) {
    this.grantType = grantType;
  }

  public IamxTokenRequest redirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

   /**
   * Get redirectUri
   * @return redirectUri
  **/
  @ApiModelProperty(value = "")
  public String getRedirectUri() {
    return redirectUri;
  }

  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }

  public IamxTokenRequest clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public IamxTokenRequest code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public IamxTokenRequest codeVerifier(String codeVerifier) {
    this.codeVerifier = codeVerifier;
    return this;
  }

   /**
   * Get codeVerifier
   * @return codeVerifier
  **/
  @ApiModelProperty(value = "")
  public String getCodeVerifier() {
    return codeVerifier;
  }

  public void setCodeVerifier(String codeVerifier) {
    this.codeVerifier = codeVerifier;
  }
  
  /**
   * Ajour par Daniel JANS - Ajout du Scope
   */
  
  public IamxTokenRequest scope(String scope) {
	    this.scope = scope;
	    return this;
	  }

	   /**
	   * Get codeVerifier
	   * @return codeVerifier
	  **/
	  @ApiModelProperty(value = "")
	  public String getScope() {
	    return scope;
	  }

	  public void setScope(String scope) {
	    this.scope = scope;
	  }
  
  


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IamxTokenRequest iamxTokenRequest = (IamxTokenRequest) o;
    // Ajout Daniel JANS - Ajout du scope
    return Objects.equals(this.grantType, iamxTokenRequest.grantType) &&
        Objects.equals(this.redirectUri, iamxTokenRequest.redirectUri) &&
        Objects.equals(this.clientId, iamxTokenRequest.clientId) &&
        Objects.equals(this.code, iamxTokenRequest.code) &&
        Objects.equals(this.scope, iamxTokenRequest.scope) &&
        Objects.equals(this.codeVerifier, iamxTokenRequest.codeVerifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grantType, redirectUri, clientId, code, codeVerifier,scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IamxTokenRequest {\n");
    
    sb.append("    grantType: ").append(toIndentedString(grantType)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    codeVerifier: ").append(toIndentedString(codeVerifier)).append("\n");
    // Ajout Daniel JANS - Ajout du Scope
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}