/*
 * IAMx oAuth Tokens Management
 * More informations here(https://wiki.bnc.ca/display/IAMAS/IAMx+Documents)
 *
 * OpenAPI spec version: 1.2.5
 * Contact: support.IAM@bnc.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.auth.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * IamxProspectRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-05T16:39:48.642-05:00")
public class IamxProspectRequest {
  @JsonProperty("reCaptcha")
  private String reCaptcha = null;

  public IamxProspectRequest reCaptcha(String reCaptcha) {
    this.reCaptcha = reCaptcha;
    return this;
  }

   /**
   * Get reCaptcha
   * @return reCaptcha
  **/
  @ApiModelProperty(value = "")
  public String getReCaptcha() {
    return reCaptcha;
  }

  public void setReCaptcha(String reCaptcha) {
    this.reCaptcha = reCaptcha;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IamxProspectRequest iamxProspectRequest = (IamxProspectRequest) o;
    return Objects.equals(this.reCaptcha, iamxProspectRequest.reCaptcha);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reCaptcha);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IamxProspectRequest {\n");
    
    sb.append("    reCaptcha: ").append(toIndentedString(reCaptcha)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

