/*
 * IAMx oAuth Tokens Management
 * More informations here(https://wiki.bnc.ca/display/IAMAS/IAMx+Documents)
 *
 * OpenAPI spec version: 1.2.5
 * Contact: support.IAM@bnc.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bnc.spti.rbo.auth.invoker;

import com.fasterxml.jackson.databind.util.StdDateFormat;
import java.text.FieldPosition;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Date;


public class RFC3339DateFormat extends StdDateFormat  {

  private static final DateTimeFormatter RFC_3339_FORMATTER = DateTimeFormatter.ISO_OFFSET_DATE_TIME;

  // Same as ISO8601DateFormat but serializing milliseconds.
  @Override
  public StringBuffer format(Date date, StringBuffer toAppendTo, FieldPosition fieldPosition) {
    String formatted = OffsetDateTime.ofInstant(date.toInstant(), ZoneOffset.UTC)
            .format(RFC_3339_FORMATTER);
    toAppendTo.append(formatted);
    return toAppendTo;
  }

}