/*
 * ECM API DocManagement
 * List of all endpoints used in API Document Management
 *
 * OpenAPI spec version: 4.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.docs4.model;

import java.util.Objects;
import com.bnc.spti.rbo.docs4.model.DocumentBo;
import com.bnc.spti.rbo.docs4.model.SearchInfosResponse;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * APISearchResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-17T09:20:33.591-04:00")
public class APISearchResponse {
  @JsonProperty("documents")
  private List<DocumentBo> documents = null;

  @JsonProperty("searchInfos")
  private SearchInfosResponse searchInfos = null;

  public APISearchResponse documents(List<DocumentBo> documents) {
    this.documents = documents;
    return this;
  }

  public APISearchResponse addDocumentsItem(DocumentBo documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<DocumentBo>();
    }
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  @ApiModelProperty(value = "")
  public List<DocumentBo> getDocuments() {
    return documents;
  }

  public void setDocuments(List<DocumentBo> documents) {
    this.documents = documents;
  }

  public APISearchResponse searchInfos(SearchInfosResponse searchInfos) {
    this.searchInfos = searchInfos;
    return this;
  }

   /**
   * Get searchInfos
   * @return searchInfos
  **/
  @ApiModelProperty(value = "")
  public SearchInfosResponse getSearchInfos() {
    return searchInfos;
  }

  public void setSearchInfos(SearchInfosResponse searchInfos) {
    this.searchInfos = searchInfos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APISearchResponse apISearchResponse = (APISearchResponse) o;
    return Objects.equals(this.documents, apISearchResponse.documents) &&
        Objects.equals(this.searchInfos, apISearchResponse.searchInfos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documents, searchInfos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APISearchResponse {\n");
    
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    searchInfos: ").append(toIndentedString(searchInfos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

