/*
 * ECM API DocManagement
 * List of all endpoints used in API Document Management
 *
 * OpenAPI spec version: 4.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.docs4.model;

import java.util.Objects;
import com.bnc.spti.rbo.docs4.model.SearchCriteriaRequest;
import com.bnc.spti.rbo.docs4.model.SearchRequest;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ClientSearchRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-17T09:20:33.591-04:00")
public class ClientSearchRequest {
  @JsonProperty("searchCriteriaRequest")
  private SearchCriteriaRequest searchCriteriaRequest = null;

  @JsonProperty("searchRequest")
  private SearchRequest searchRequest = null;

  public ClientSearchRequest searchCriteriaRequest(SearchCriteriaRequest searchCriteriaRequest) {
    this.searchCriteriaRequest = searchCriteriaRequest;
    return this;
  }

   /**
   * Get searchCriteriaRequest
   * @return searchCriteriaRequest
  **/
  @ApiModelProperty(value = "")
  public SearchCriteriaRequest getSearchCriteriaRequest() {
    return searchCriteriaRequest;
  }

  public void setSearchCriteriaRequest(SearchCriteriaRequest searchCriteriaRequest) {
    this.searchCriteriaRequest = searchCriteriaRequest;
  }

  public ClientSearchRequest searchRequest(SearchRequest searchRequest) {
    this.searchRequest = searchRequest;
    return this;
  }

   /**
   * Get searchRequest
   * @return searchRequest
  **/
  @ApiModelProperty(value = "")
  public SearchRequest getSearchRequest() {
    return searchRequest;
  }

  public void setSearchRequest(SearchRequest searchRequest) {
    this.searchRequest = searchRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientSearchRequest clientSearchRequest = (ClientSearchRequest) o;
    return Objects.equals(this.searchCriteriaRequest, clientSearchRequest.searchCriteriaRequest) &&
        Objects.equals(this.searchRequest, clientSearchRequest.searchRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(searchCriteriaRequest, searchRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientSearchRequest {\n");
    
    sb.append("    searchCriteriaRequest: ").append(toIndentedString(searchCriteriaRequest)).append("\n");
    sb.append("    searchRequest: ").append(toIndentedString(searchRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

