/*
 * ECM API DocManagement
 * List of all endpoints used in API Document Management
 *
 * OpenAPI spec version: 4.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.docs4.model;

import java.util.Objects;
import com.bnc.spti.rbo.docs4.model.Criteria;
import com.bnc.spti.rbo.docs4.model.SelectCriteria;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SearchCriteriaRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-17T09:20:33.591-04:00")
public class SearchCriteriaRequest {
  @JsonProperty("criteria")
  private List<Criteria> criteria = null;

  @JsonProperty("pageNumber")
  private Integer pageNumber = null;

  @JsonProperty("pageSize")
  private Integer pageSize = null;

  @JsonProperty("properties")
  private List<SelectCriteria> properties = null;

  public SearchCriteriaRequest criteria(List<Criteria> criteria) {
    this.criteria = criteria;
    return this;
  }

  public SearchCriteriaRequest addCriteriaItem(Criteria criteriaItem) {
    if (this.criteria == null) {
      this.criteria = new ArrayList<Criteria>();
    }
    this.criteria.add(criteriaItem);
    return this;
  }

   /**
   * Get criteria
   * @return criteria
  **/
  @ApiModelProperty(value = "")
  public List<Criteria> getCriteria() {
    return criteria;
  }

  public void setCriteria(List<Criteria> criteria) {
    this.criteria = criteria;
  }

  public SearchCriteriaRequest pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Get pageNumber
   * @return pageNumber
  **/
  @ApiModelProperty(value = "")
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public SearchCriteriaRequest pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @ApiModelProperty(value = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public SearchCriteriaRequest properties(List<SelectCriteria> properties) {
    this.properties = properties;
    return this;
  }

  public SearchCriteriaRequest addPropertiesItem(SelectCriteria propertiesItem) {
    if (this.properties == null) {
      this.properties = new ArrayList<SelectCriteria>();
    }
    this.properties.add(propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(value = "")
  public List<SelectCriteria> getProperties() {
    return properties;
  }

  public void setProperties(List<SelectCriteria> properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchCriteriaRequest searchCriteriaRequest = (SearchCriteriaRequest) o;
    return Objects.equals(this.criteria, searchCriteriaRequest.criteria) &&
        Objects.equals(this.pageNumber, searchCriteriaRequest.pageNumber) &&
        Objects.equals(this.pageSize, searchCriteriaRequest.pageSize) &&
        Objects.equals(this.properties, searchCriteriaRequest.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(criteria, pageNumber, pageSize, properties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchCriteriaRequest {\n");
    
    sb.append("    criteria: ").append(toIndentedString(criteria)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

