/*
 * ECM API DocManagement
 * List of all endpoints used in API Document Management
 *
 * OpenAPI spec version: 4.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.docs4.model;

import java.util.Objects;
import com.bnc.spti.rbo.docs4.model.SelectionCriteria;
import com.bnc.spti.rbo.docs4.model.Sort;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SearchRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-17T09:20:33.591-04:00")
public class SearchRequest {
  @JsonProperty("pageNumber")
  private String pageNumber = null;

  @JsonProperty("pageSize")
  private String pageSize = null;

  @JsonProperty("selectProperties")
  private List<String> selectProperties = null;

  @JsonProperty("selectionCriteria")
  private SelectionCriteria selectionCriteria = null;

  @JsonProperty("sort")
  private Sort sort = null;

  @JsonProperty("versionning")
  private String versionning = null;

  public SearchRequest pageNumber(String pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Get pageNumber
   * @return pageNumber
  **/
  @ApiModelProperty(value = "")
  public String getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(String pageNumber) {
    this.pageNumber = pageNumber;
  }

  public SearchRequest pageSize(String pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @ApiModelProperty(value = "")
  public String getPageSize() {
    return pageSize;
  }

  public void setPageSize(String pageSize) {
    this.pageSize = pageSize;
  }

  public SearchRequest selectProperties(List<String> selectProperties) {
    this.selectProperties = selectProperties;
    return this;
  }

  public SearchRequest addSelectPropertiesItem(String selectPropertiesItem) {
    if (this.selectProperties == null) {
      this.selectProperties = new ArrayList<String>();
    }
    this.selectProperties.add(selectPropertiesItem);
    return this;
  }

   /**
   * Get selectProperties
   * @return selectProperties
  **/
  @ApiModelProperty(value = "")
  public List<String> getSelectProperties() {
    return selectProperties;
  }

  public void setSelectProperties(List<String> selectProperties) {
    this.selectProperties = selectProperties;
  }

  public SearchRequest selectionCriteria(SelectionCriteria selectionCriteria) {
    this.selectionCriteria = selectionCriteria;
    return this;
  }

   /**
   * Get selectionCriteria
   * @return selectionCriteria
  **/
  @ApiModelProperty(value = "")
  public SelectionCriteria getSelectionCriteria() {
    return selectionCriteria;
  }

  public void setSelectionCriteria(SelectionCriteria selectionCriteria) {
    this.selectionCriteria = selectionCriteria;
  }

  public SearchRequest sort(Sort sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  @ApiModelProperty(value = "")
  public Sort getSort() {
    return sort;
  }

  public void setSort(Sort sort) {
    this.sort = sort;
  }

  public SearchRequest versionning(String versionning) {
    this.versionning = versionning;
    return this;
  }

   /**
   * Get versionning
   * @return versionning
  **/
  @ApiModelProperty(value = "")
  public String getVersionning() {
    return versionning;
  }

  public void setVersionning(String versionning) {
    this.versionning = versionning;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchRequest searchRequest = (SearchRequest) o;
    return Objects.equals(this.pageNumber, searchRequest.pageNumber) &&
        Objects.equals(this.pageSize, searchRequest.pageSize) &&
        Objects.equals(this.selectProperties, searchRequest.selectProperties) &&
        Objects.equals(this.selectionCriteria, searchRequest.selectionCriteria) &&
        Objects.equals(this.sort, searchRequest.sort) &&
        Objects.equals(this.versionning, searchRequest.versionning);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageNumber, pageSize, selectProperties, selectionCriteria, sort, versionning);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchRequest {\n");
    
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    selectProperties: ").append(toIndentedString(selectProperties)).append("\n");
    sb.append("    selectionCriteria: ").append(toIndentedString(selectionCriteria)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    versionning: ").append(toIndentedString(versionning)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

