/*
 * ECM API DocManagement
 * List of all endpoints used in API Document Management
 *
 * OpenAPI spec version: 4.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.spti.rbo.docs4.model;

import java.util.Objects;
import com.bnc.spti.rbo.docs4.model.CriteriaMapping;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SelectionCriteria
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-17T09:20:33.591-04:00")
public class SelectionCriteria {
  @JsonProperty("criteriaMapping")
  private List<CriteriaMapping> criteriaMapping = null;

  @JsonProperty("query")
  private String query = null;

  public SelectionCriteria criteriaMapping(List<CriteriaMapping> criteriaMapping) {
    this.criteriaMapping = criteriaMapping;
    return this;
  }

  public SelectionCriteria addCriteriaMappingItem(CriteriaMapping criteriaMappingItem) {
    if (this.criteriaMapping == null) {
      this.criteriaMapping = new ArrayList<CriteriaMapping>();
    }
    this.criteriaMapping.add(criteriaMappingItem);
    return this;
  }

   /**
   * Get criteriaMapping
   * @return criteriaMapping
  **/
  @ApiModelProperty(value = "")
  public List<CriteriaMapping> getCriteriaMapping() {
    return criteriaMapping;
  }

  public void setCriteriaMapping(List<CriteriaMapping> criteriaMapping) {
    this.criteriaMapping = criteriaMapping;
  }

  public SelectionCriteria query(String query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(value = "")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectionCriteria selectionCriteria = (SelectionCriteria) o;
    return Objects.equals(this.criteriaMapping, selectionCriteria.criteriaMapping) &&
        Objects.equals(this.query, selectionCriteria.query);
  }

  @Override
  public int hashCode() {
    return Objects.hash(criteriaMapping, query);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectionCriteria {\n");
    
    sb.append("    criteriaMapping: ").append(toIndentedString(criteriaMapping)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

