/*
 * ECM API DocManagement GCP
 * List of all endpoints used in API Document Management V5
 *
 * The version of the OpenAPI document: 5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.cogitosum.rdi.api.ApiException;
import com.cogitosum.rdi.api.api.SystemEmployeeApiDocumentManagementV5Api;
import com.cogitosum.rdi.api.model.Document;

import java.io.File;
import com.cogitosum.rdi.api.model.SearchCriteria;
import com.cogitosum.rdi.api.model.SearchResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for SystemEmployeeApiDocumentManagementV5Api
 */
@Disabled
public class SystemEmployeeApiDocumentManagementV5ApiTest {

    private final SystemEmployeeApiDocumentManagementV5Api api = new SystemEmployeeApiDocumentManagementV5Api();

    /**
     * Create new document
     *
     * Create Document and returns DocID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createDocumentPrivateUsingPOST1Test() throws ApiException {
        String businessViewId = null;
        File content = null;
        File metadata = null;
        Object response = api.createDocumentPrivateUsingPOST1(businessViewId, content, metadata);
        // TODO: test validations
    }

    /**
     * Get document
     *
     * Get Document by DocID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDocumentUsingGET1Test() throws ApiException {
        String businessViewId = null;
        String docId = null;
        Document response = api.getDocumentUsingGET1(businessViewId, docId);
        // TODO: test validations
    }

    /**
     * Search documents
     *
     * Search Document by criteria
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchUsingPOST1Test() throws ApiException {
        String businessViewId = null;
        SearchCriteria searchCriteria = null;
        SearchResult response = api.searchUsingPOST1(businessViewId, searchCriteria);
        // TODO: test validations
    }

}
